name: udales
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  # Tests
  - numpy
  - scipy
  - xarray
  - netCDF4
  - h5netcdf
  - trimesh
  - shapely
  - matplotlib
  - plotly
  - f90nml
  - numba
  - pvlib
  - meson
  - ninja
  # Docs
  - graphviz
  - mkdocs-material
  - mkdocs-material-extensions
  - pip:
    - triangle
    - mkdocs-bibtex
    - ford
