#!/bin/bash
#
#SBATCH --nodes=1
#SBATCH --tasks-per-node=1
#SBATCH --cpus-per-task=128
#SBATCH --job-name=job_synthflow
#SBATCH --account=n02-ASSURE
#SBATCH --partition=standard
#SBATCH --qos=standard
#SBATCH --time=24:00:0


# Directory paths (modify these for your machine)
export OMP_NUM_THREADS=128
export DA_EXPDIR=.../experiments/{expnr}      # Experiment directory
export DA_TOOLSDIR=.../u-dales/tools/         # u-DALES tools directory
export DA_WORKDIR=.../outputs/driver_outputs  # Output directory for driver files

${DA_TOOLSDIR}/generate_synthetic_inflow.sh ${DA_EXPDIR}