#!/bin/bash
#
#SBATCH --nodes=1
#SBATCH --tasks-per-node=1
#SBATCH --cpus-per-task=1
#SBATCH --job-name=job_test_psi
#SBATCH --account=n02-ASSURE
#SBATCH --partition=serial
#SBATCH --qos=serial
#SBATCH --time=1:00:00
####SBATCH --mem=125G

#export DA_EXPDIR=/work/n02/n02/jh6016c/synInflow_gen/771
#export DA_TOOLSDIR=/work/n02/n02/jh6016c/tools
#export DA_WORKDIR=/work/n02/n02/jh6016c/synInflow_gen/771/driver_outputs

module load cray-fftw

ftn -O3 test_calc_psi.f90 -o test_calc_psi

srun --ntasks=1 --cpus-per-task=1 ./test_calc_psi

#/work/n02/n02/jh6016c/tools/generate_synthetic_inflow.sh /work/n02/n02/jh6016c/synInflow_gen/771
