uDALES – uDALES
uDALES Program
125 statements
Source File
Uses
initfac
modtstep
modstartup
tests
modsave
modadvection
modforces
modstat_nc
modpois
modglobal
modheatpump
moddriver
modboundary
modtimedep
modthermodynamics
modibm
modpurifiers
modstatsdump
modEB
modsubgrid
modfields
modscalsource
modchecksim
modfielddump
modmpi
vegetation
Calls
Subroutines
subroutine execute_runmode_actions()
Arguments
None
Source Code
program uDALES
!!----------------------------------------------------------------
!!     0.0    USE STATEMENTS FOR CORE MODULES
!!----------------------------------------------------------------
  use modmpi,            only : initmpi,exitmpi,starttimer
  use modglobal,         only : initglobal,rk3step,timeleft
  use modglobal,         only : runmode,RUN_COLDSTART,RUN_WARMSTART,RUN_DRIVER,RUN_STRATSTART,TEST_SPARSE_IJK,TEST_2DCOMP_INIT_EXIT,TEST_MPI_OPERATORS
  use modstartup,        only : readnamelists,init2decomp,checkinitvalues,readinitfiles,exitmodules
  use modfields,         only : initfields
  use modsave,           only : writerestartfiles
  use modboundary,       only : initboundary,boundary,grwdamp,halos
  use modthermodynamics, only : initthermodynamics,thermodynamics
  use modsubgrid,        only : initsubgrid,subgrid
  use modforces,         only : calcfluidvolumes,forces,coriolis,lstend,fixuinf1,fixuinf2,fixthetainf,nudge,masscorr,shiftedPBCs,periodicEBcorr
  use modpois,           only : initpois,poisson
  use modibm,            only : initibm,createmasks,ibmwallfun,ibmnorm,bottom
  use vegetation,        only : init_vegetation, vegetation_forcing
  use modpurifiers,      only : createpurifiers,purifiers
  use modheatpump,       only : init_heatpump,heatpump,exit_heatpump
  use initfac,           only : readfacetfiles
  use modEB,             only : initEB,EB
  use moddriver,         only : initdriver
  use modadvection,      only : advection
  use modtstep,          only : tstep_update,tstep_integrate
  use modscalsource,     only : createscals,scalsource
!----------------------------------------------------------------
!     0.1     USE STATEMENTS FOR ADDONS STATISTICAL ROUTINES
!----------------------------------------------------------------
  use modchecksim,     only : initchecksim,checksim
  use modstat_nc,      only : initstat_nc
  use modfielddump,    only : initfielddump,fielddump,exitfielddump
  use modstatsdump,    only : initstatsdump,statsdump,exitstatsdump    !tg3315
  use modtimedep,      only : inittimedep,timedep
  use tests,           only : tests_read_sparse_ijk,tests_2decomp_init_exit,tests_mpi_operators
  implicit none
!----------------------------------------------------------------
!     0      READ NAMELISTS,INITIALISE GRID, CONSTANTS AND FIELDS
!----------------------------------------------------------------
  call initmpi
  !call startup
  call readnamelists
  call init2decomp
  call checkinitvalues
  call initglobal
  ! Execute tests if needed
  call execute_runmode_actions
  call initfields
  call initboundary
  call initthermodynamics
  call initsubgrid
  ! call initinlet
  call initdriver
  call initpois
  call readfacetfiles
  ! These should be combined once file format is sorted
  call initibm
  call createmasks
  call calcfluidvolumes
  call readinitfiles
  call createscals
!---------------------------------------------------------
!      2     INITIALIZE STATISTICAL ROUTINES AND ADD-ONS
!---------------------------------------------------------
  call initchecksim ! Could be deprecated
  call initstat_nc ! Could be deprecated
  call initstatsdump
  call initEB
  call inittimedep
  call initfielddump
  call boundary
  call init_vegetation
  call createpurifiers
  call init_heatpump
  !call fielddump
!------------------------------------------------------
!   3.0   MAIN TIME LOOP
!------------------------------------------------------
  !write(*,*) 'Starting rank ', myid
  call starttimer
  do while ((timeleft>0) .or. (rk3step < 3))
    call tstep_update
    call timedep
!-----------------------------------------------------
!   3.2   ADVECTION AND DIFFUSION
!-----------------------------------------------------
    call advection ! includes predicted pressure gradient term
    call shiftedPBCs
    call subgrid
!-----------------------------------------------------
!   3.3   THE SURFACE LAYER
!-----------------------------------------------------
    call bottom
!-----------------------------------------------------
!   3.4   REMAINING TERMS
!-----------------------------------------------------
    call coriolis       !remaining terms of ns equation
    call forces         !remaining terms of ns equation
    call lstend         !large scale forcings
    call nudge          ! nudge top cells of fields to enforce steady-state
    call ibmwallfun     ! immersed boundary forcing: only shear forces.
    call periodicEBcorr
    call masscorr       ! correct pred. velocity pup to get correct mass flow
    call ibmnorm        ! immersed boundary forcing: set normal velocities to zero
    call EB
    call vegetation_forcing
    call heatpump
    call scalsource     ! adds continuous forces in specified region of domain
!------------------------------------------------------
!   3.4   EXECUTE ADD ONS
!------------------------------------------------------
    call fixuinf2
    call fixuinf1
!-----------------------------------------------------------------------
!   3.5  PRESSURE FLUCTUATIONS, TIME INTEGRATION AND BOUNDARY CONDITIONS
!-----------------------------------------------------------------------
    call grwdamp        !damping at top of the model
    call poisson
    call purifiers      !placing of purifiers here may need to be checked
    call tstep_integrate
    call halos
    call checksim
    call fielddump
    call statsdump
    call boundary
    !call fixthetainf ! deprecated
!-----------------------------------------------------
!   3.6   LIQUID WATER CONTENT AND DIAGNOSTIC FIELDS
!-----------------------------------------------------
    call thermodynamics
!-----------------------------------------------------
!   3.7  WRITE RESTARTFILES AND DO STATISTICS
!------------------------------------------------------
    call writerestartfiles
  end do
!-------------------------------------------------------
!             END OF TIME LOOP
!-------------------------------------------------------
!--------------------------------------------------------
!    4    FINALIZE ADD ONS AND THE MAIN PROGRAM
!-------------------------------------------------------
  call exitfielddump
  call exitstatsdump     !tg3315
  call exit_heatpump
  !call exitmodules
  !call exittest
  call exitmpi
contains
  subroutine execute_runmode_actions
    logical :: test_failed
    logical :: invalid_runmode
    test_failed = .false.
    invalid_runmode = .false.
    select case (runmode)
      case (RUN_COLDSTART, RUN_WARMSTART, RUN_DRIVER, RUN_STRATSTART)
        return
        ! Normal execution mode, do nothing special here
      case (TEST_SPARSE_IJK)
        ! Execute tests for reading sparse arrays
        test_failed = .not. tests_read_sparse_ijk()
      case (TEST_MPI_OPERATORS)
        test_failed = .not. tests_mpi_operators()
      case (TEST_2DCOMP_INIT_EXIT)
        call tests_2decomp_init_exit
      case default
        write(*,*) 'Unknown runmode:', runmode
        invalid_runmode = .true.
    end select
    call exitmpi
    if (invalid_runmode) then
      stop 1
    end if
    ! Return appropriate exit code for unit tests:
    ! 0 = success, 1 = failure
    if (test_failed) then
      stop 1
    else
      stop 0
    end if
  end subroutine execute_runmode_actions
end program uDALES
Call graph
udales calls initpois, poisson, advection, bottom, boundary, calcfluidvolumes, checkinitvalues, checksim, coriolis, createmasks, createpurifiers, createscals, eb, execute_runmode_actions, exit_heatpump, exitfielddump, exitmpi, exitstatsdump, fielddump, fixuinf1, fixuinf2, forces, grwdamp, halos, heatpump, ibmnorm, ibmwallfun, init2decomp, init_heatpump, init_vegetation, initboundary, initchecksim, initdriver, initeb, initfielddump, initfields, initglobal, initibm, initmpi, initstat_nc, initstatsdump, initsubgrid, initthermodynamics, inittimedep, lstend, masscorr, nudge, periodicebcorr, purifiers, readfacetfiles, readinitfiles, readnamelists, scalsource, shiftedpbcs, starttimer, statsdump, subgrid, thermodynamics, timedep, tstep_integrate, tstep_update, vegetation_forcing, writerestartfiles
advection calls advecc_2nd, advecc_kappa, advecc_upw, advecu_2nd, advecv_2nd, advecw_2nd
bottom calls wfmneutral, wfuno
boundary calls driverchunkread, drivergen, fluxtop, fluxtopscal, valuetop, valuetopscal, xmi_driver, xmi_profile, xmo_convective, xqi_driver, xqi_profile, xqo_convective, xsi_custom, xsi_driver, xsi_profile, xso_convective, xti_driver, xti_profile, xto_convective, ymi_profile, ymo_convective, yqi_profile, yqo_convective, ysi_profile, yso_convective, yti_profile, yto_convective
calcfluidvolumes calls fluidvolume, uoutletarea, voutletarea
checkinitvalues calls mpi_bcast, mpi_finalize
checksim calls calccourant, calcdiffnr, chkdiv
createmasks calls mpi_allreduce
createpurifiers calls mpi_bcast
createscals calls mpi_bcast
eb calls writestat_nc, mpi_bcast, calclw, gaussji, intqh, matinv4, updategr, writestat_1d_nc, writestat_2d_nc
execute_runmode_actions calls exitmpi, tests_2decomp_init_exit, tests_mpi_operators, tests_read_sparse_ijk
exitfielddump calls exitstat_nc
exitmpi calls decomp_2d_finalize, mpi_finalize, mpi_wtime
fielddump calls writestat_nc
fixuinf2 calls detfreestream
halos calls exchange_halo_z, xm_periodic, xq_periodic, xs_periodic, xt_periodic, ym_periodic, yq_periodic, ys_periodic, yt_periodic
heatpump calls zsize
ibmnorm calls advecc2nd_corr_conservative, advecc2nd_corr_liberal, solid
ibmwallfun calls writestat_nc, diffc_corr, diffu_corr, diffv_corr, diffw_corr, wallfunheat, wallfunmom, writestat_1d_nc
init2decomp calls decomp_2d_init, mpi_cart_coords, mpi_cart_shift
init_heatpump calls mpi_bcast, zend, zstart
init_vegetation calls exchange_halo_z, mpi_barrier, mpi_bcast, init_vegetation_legacy, read_sparse_ijk, read_sparse_real
initchecksim calls mpi_bcast
initdriver calls zend, zstart
initeb calls define_nc, gaussji, matinv4, ncinfo, open_nc, writestat_dims_nc
initfielddump calls mpi_bcast, define_nc, ncinfo, open_nc, writestat_dims_nc
initfields calls alloc_z
initglobal calls float, mpi_bcast, xsize, ysize, zend, zsize, zstart
initibm calls exchange_halo_z, define_nc, initibmnorm, initibmwallfun, ncinfo, open_nc, solid, writestat_dims_nc
initmpi calls mpi_comm_rank, mpi_comm_size, mpi_init
initstatsdump calls mpi_bcast, define_nc, ncinfo, open_nc, writestat_dims_nc, zend, zstart
initsubgrid calls subgridnamelist
inittimedep calls timedep, mpi_bcast
masscorr calls avexy_ibm, sumy_ibm
periodicebcorr calls mpi_allreduce
readfacetfiles calls mpi_bcast, nf90_get_var, nf90_inq_varid, nf90_open, qsat
readinitfiles calls halos, thermodynamics, mpi_bcast, avexy_ibm, calc_halflev, drivergen, randomize_field, readdriverfile, readdriverfile_chunk, readinletfile, readrestartfiles, slabsum
readnamelists calls mpi_bcast
shiftedpbcs calls zstart
starttimer calls mpi_wtime
statsdump calls writestat_nc, avexy_ibm, avey_ibm, tkestatsdump, veg_to_3d_cell, veg_to_3d_face, veg_to_3d_sv, writestat_1d_nc
subgrid calls closure, diffc, diffe, diffu, diffv, diffw, sources
thermodynamics calls avexy_ibm, calc_halflev, calthv, diagfld, thermo
timedep calls timedeplw, timedepnudge, timedepsurf, timedepsw
tstep_integrate calls chem
tstep_update calls mpi_allreduce
vegetation_forcing calls reset_vegetation_sources, vegetation_forcing_legacy, vegetation_forcing_sveg
writerestartfiles calls mpi_abort, mpi_bcast
writestat_nc calls writestat_1d_nc, writestat_2d_nc, writestat_3d_nc, writestat_3d_short_nc, writestat_time_nc
advecc_kappa calls rlim
avexy_ibm calls mpi_allreduce
avey_ibm calls mpi_allreduce
calccourant calls mpi_allreduce
calcdiffnr calls mpi_allreduce
chkdiv calls mpi_allreduce
closure calls closurebc
define_nc calls nf90_inq_varid, nf90_def_var, nf90_enddef, nf90_inq_dimid, nf90_put_att, nf90_redef, nchandle_error
diagfld calls avexy_ibm, fromztop
driverchunkread calls readdriverfile_chunk
drivergen calls writedriverfile
exitstat_nc calls nf90_close, nchandle_error
fluidvolume calls avexy_ibm
initibmnorm calls read_sparse_ijk
initibmwallfun calls mpi_bcast, read_sparse_ijk, zend, zstart, alignment, plane_line_intersection
intqh calls mpi_allreduce
open_nc calls nf90_get_var, nf90_inq_varid, nf90_open, nf90_create, nf90_def_dim, nf90_def_var, nf90_enddef, nf90_inq_dimid, nf90_inquire, nf90_inquire_dimension, nf90_put_att, nf90_sync
randomize_field calls zstart
read_sparse_ijk calls mpi_bcast, zend, zstart
read_sparse_real calls mpi_bcast
readinletfile calls excjs, yinterpolate, zinterpolate, zinterpolatet, zinterpolatew
readrestartfiles calls zinterpolate1d, zinterpolate2d, zinterpolatet1d, zinterpolatew1d
slabsum calls mpi_allreduce
subgridnamelist calls mpi_bcast
sumy_ibm calls mpi_allreduce
tests_mpi_operators calls createmasks, initfields, initibm, readfacetfiles, mpi_allreduce, avexy_ibm, avey_ibm, sumy_ibm, sumx_ibm
tests_read_sparse_ijk calls initibm, readfacetfiles, read_sparse_ijk, compare_boundary, compare_solid
tkestatsdump calls exchange_halo_z, avexy_ibm
uoutletarea calls sumy_ibm
updategr calls qsat
voutletarea calls sumx_ibm
wallfunheat calls mpi_allreduce, zstart, heat_transfer_coef_flux, interp_velocity_c, is_equal, local_coords, moist_flux, trilinear_interp_var
wallfunmom calls mpi_allreduce, zstart, alignment, is_equal, local_coords, mom_transfer_coef_neutral, mom_transfer_coef_stability, trilinear_interp_var
wfuno calls unoh, unom
writestat_1d_nc calls nf90_inq_varid, nf90_put_var, nf90_sync
writestat_2d_nc calls nf90_inq_varid, nf90_put_var, nf90_sync
writestat_dims_nc calls nf90_inq_varid, nf90_inquire_dimension, nf90_put_var
xsi_custom calls zstart
alignment calls is_equal
closurebc calls exchange_halo_z, reassure_fluxtop_boundary
excjs calls mpi_isend, mpi_recv, mpi_wait
local_coords calls is_equal, cross_product
nchandle_error calls nf90_strerror
sumx_ibm calls mpi_allreduce
trilinear_interp_var calls zstart, eval_corners, trilinear_interp
writestat_3d_nc calls nf90_inq_varid, nf90_put_var, nf90_sync
writestat_3d_short_nc calls nf90_inq_varid, nf90_put_var, nf90_sync
writestat_time_nc calls nf90_inq_varid, nf90_put_var, nf90_sync
reassure_fluxtop_boundary calls fluxtop, fluxtopscal