alignment – uDALES
alignment Function
20 statements
Source File
public function alignment(n)
Uses
modglobal
Arguments
Type Intent Optional Attributes Name
real, intent(in), dimension(3) :: n
Return Value integer
Calls
Called by
Source Code
   integer function alignment(n)
     ! returns an integer determining whether a unit vector n is aligned with the
     ! coordinates axes.
     use modglobal, only : xhat, yhat, zhat
     implicit none
     real, dimension(3), intent(in) :: n ! must be unit vector
     if     (is_equal(n, xhat)) then
       alignment = 1
     elseif (is_equal(n, yhat)) then
       alignment = 2
     elseif (is_equal(n, zhat)) then
       alignment = 3
     elseif (is_equal(n, -xhat)) then
       alignment = -1
     elseif (is_equal(n, -yhat)) then
       alignment = -2
     elseif (is_equal(n, -zhat)) then
       alignment = -3
     else
       alignment = 0
     end if
   end function alignment
Call graph
alignment calls is_equal
initibmwallfun calls alignment
wallfunmom calls alignment
ibmwallfun calls wallfunmom
initibm calls initibmwallfun
dalesurban calls ibmwallfun, initibm