avexy_ibm – uDALES
avexy_ibm Subroutine
30 statements
Source File
public subroutine avexy_ibm(aver, var, ib, ie, jb, je, kb, ke, ih, jh, kh, II, IIs, lnan)
Arguments
Type Intent Optional Attributes Name
real :: aver(kb:ke+kh)
real :: var(ib:ie,jb:je,kb:ke+kh)
integer :: ib
integer :: ie
integer :: jb
integer :: je
integer :: kb
integer :: ke
integer :: ih
integer :: jh
integer :: kh
integer :: II(ib:ie,jb:je,kb:ke+kh)
integer :: IIs(kb:ke+kh)
logical :: lnan
Calls
Called by
Source Code
  subroutine avexy_ibm(aver,var,ib,ie,jb,je,kb,ke,ih,jh,kh,II,IIs,lnan)
    implicit none
    integer :: ib,ie,jb,je,kb,ke,ih,jh,kh
    real    :: aver(kb:ke+kh)
    real    :: var(ib:ie,jb:je,kb:ke+kh)
    integer :: II(ib:ie,jb:je,kb:ke+kh)
    integer :: IIs(kb:ke+kh)
    integer :: IId(kb:ke+kh)
    real    :: averl(kb:ke+kh)
    real    :: avers(kb:ke+kh)
    integer :: k
    logical :: lnan
    averl       = 0.
    avers       = 0.
    do k=kb,ke+kh
      averl(k) = sum(var(ib:ie,jb:je,k)*II(ib:ie,jb:je,k))
    enddo
    IId = IIs
    ! tg3315 22.03.19 - if not calculating stats and all blocks on lowest layer...
    ! should not be necessary but value at kb is used in modthermo so reasonable value must
    ! be assigned. Potentially should leave as before and only account for in modthermo...
    if ((.not. lnan) .and. (IId(kb)==0)) then
      averl(kb) = sum(var(ib:ie,jb:je,kb))
      IId(kb) = IId(ke)
    end if
    call MPI_ALLREDUCE(averl, avers, ke+kh-kb+1,  MY_REAL, &
                          MPI_SUM, comm3d,mpierr)
    where (IId==0)
      aver = -999.
    elsewhere
      aver = avers/IId
    endwhere
    return
  end subroutine avexy_ibm
Call graph
avexy_ibm calls mpi_allreduce
bcpup calls avexy_ibm
diagfld calls avexy_ibm
fluidvolume calls avexy_ibm
masscorr calls avexy_ibm
readinitfiles calls avexy_ibm, thermodynamics
statsdump calls avexy_ibm, tkestatsdump
tests_mpi_operators calls avexy_ibm
thermodynamics calls avexy_ibm, diagfld
tkestatsdump calls avexy_ibm
calcfluidvolumes calls fluidvolume
execute_runmode_actions calls tests_mpi_operators
udales calls masscorr, readinitfiles, statsdump, thermodynamics, calcfluidvolumes, execute_runmode_actions