calcfluidvolumes – uDALES
calcfluidvolumes Subroutine
11 statements
Source File
public subroutine calcfluidvolumes()
Uses
modfields
Arguments
None
Calls
Called by
Source Code
  subroutine calcfluidvolumes
    !> calculates fluid volume and outlet areas, excluding blocks
    !> and saves it to variables from modfields
    use modfields, only : uoutarea, voutarea, fluidvol
    implicit none
    real :: volume
    ! calculate outlet area
    call uoutletarea(volume)
    uoutarea = volume
    ! calculate outlet area
    call voutletarea(volume)
    voutarea = volume
    ! calculate fluid volume
    call fluidvolume(volume)
    fluidvol = volume
  end subroutine calcfluidvolumes
Call graph
calcfluidvolumes calls fluidvolume, uoutletarea, voutletarea
fluidvolume calls avexy_ibm
uoutletarea calls sumy_ibm
voutletarea calls sumx_ibm
avexy_ibm calls mpi_allreduce
sumx_ibm calls mpi_allreduce
sumy_ibm calls mpi_allreduce
dalesurban calls calcfluidvolumes