cross_product – uDALES
cross_product Function
8 statements
Source File
public function cross_product(a, b)
Arguments
Type Intent Optional Attributes Name
real, intent(in), dimension(3) :: a
real, intent(in), dimension(3) :: b
Return Value real, dimension(3)
Called by
Source Code
   function cross_product(a,b)
     ! Calculate the cross product (a x b)
     implicit none
     real, dimension(3) :: cross_product
     real, dimension(3), intent(in) :: a, b
     cross_product(1) = a(2)*b(3) - a(3)*b(2)
     cross_product(2) = a(3)*b(1) - a(1)*b(3)
     cross_product(3) = a(1)*b(2) - a(2)*b(1)
   end function cross_product
Call graph
local_coords calls cross_product
wallfunheat calls local_coords
wallfunmom calls local_coords
ibmwallfun calls wallfunheat, wallfunmom
dalesurban calls ibmwallfun