driverchunkread – uDALES
driverchunkread Subroutine
11 statements
Source File
public subroutine driverchunkread()
Uses
modinletdata
modglobal
modmpi
Arguments
None
Calls
Called by
Source Code
  subroutine driverchunkread
    use modglobal,    only : timee,ibrank,idriver,lchunkread
    use modinletdata, only : storetdriver, chunkread_e
    use modmpi,       only : myid
    ! if (idriver==2 .and. lchunkread .and. timee > storetdriver(chunkread_e)) then
    !   if (myid==0) then
    !     write(6,*) 'Current timee = ', timee, '; last read storetdriver = ', storetdriver(chunkread_e), &
    !                'at driver step = ',chunkread_e,'. Hence, next driver chunk will be read now.'
    !   end if
    !   if (ibrank) call readdriverfile_chunk
    ! end if
    do while (timee > storetdriver(chunkread_e))
      if (myid==0) then
        write(6,*) 'Current timee = ', timee, '; last read storetdriver = ', storetdriver(chunkread_e), &
                   'at driver step = ',chunkread_e,'. Hence, next driver chunk will be read now.'
      end if
      if (ibrank) call readdriverfile_chunk
    end do
  end subroutine driverchunkread
Call graph
driverchunkread calls readdriverfile_chunk
boundary calls driverchunkread
dalesurban calls boundary