execute_runmode_actions – uDALES
execute_runmode_actions Subroutine
28 statements
Source File
subroutine execute_runmode_actions()
Arguments
None
Calls
Called by
Source Code
  subroutine execute_runmode_actions
    logical :: test_failed
    logical :: invalid_runmode
    test_failed = .false.
    invalid_runmode = .false.
    select case (runmode)
      case (RUN_COLDSTART, RUN_WARMSTART, RUN_DRIVER, RUN_STRATSTART)
        return
        ! Normal execution mode, do nothing special here
      case (TEST_SPARSE_IJK)
        ! Execute tests for reading sparse arrays
        test_failed = .not. tests_read_sparse_ijk()
      case (TEST_MPI_OPERATORS)
        test_failed = .not. tests_mpi_operators()
      case (TEST_2DCOMP_INIT_EXIT)
        call tests_2decomp_init_exit
      case default
        write(*,*) 'Unknown runmode:', runmode
        invalid_runmode = .true.
    end select
    call exitmpi
    if (invalid_runmode) then
      stop 1
    end if
    ! Return appropriate exit code for unit tests:
    ! 0 = success, 1 = failure
    if (test_failed) then
      stop 1
    else
      stop 0
    end if
  end subroutine execute_runmode_actions
Call graph
execute_runmode_actions calls exitmpi, tests_2decomp_init_exit, tests_mpi_operators, tests_read_sparse_ijk
exitmpi calls decomp_2d_finalize, mpi_finalize, mpi_wtime
tests_mpi_operators calls mpi_allreduce, avexy_ibm, avey_ibm, createmasks, initfields, initibm, readfacetfiles, sumx_ibm, sumy_ibm
tests_read_sparse_ijk calls compare_boundary, compare_solid, initibm, read_sparse_ijk, readfacetfiles
avexy_ibm calls mpi_allreduce
avey_ibm calls mpi_allreduce
createmasks calls mpi_allreduce
initfields calls alloc_z
initibm calls exchange_halo_z, define_nc, initibmnorm, initibmwallfun, ncinfo, open_nc, solid, writestat_dims_nc
read_sparse_ijk calls mpi_bcast, zend, zstart
readfacetfiles calls mpi_bcast, nf90_get_var, nf90_inq_varid, nf90_open, qsat
sumx_ibm calls mpi_allreduce
sumy_ibm calls mpi_allreduce
define_nc calls nf90_inq_varid, nf90_def_var, nf90_enddef, nf90_inq_dimid, nf90_put_att, nf90_redef, nchandle_error
initibmnorm calls read_sparse_ijk
initibmwallfun calls read_sparse_ijk, mpi_bcast, zend, zstart, alignment, plane_line_intersection
open_nc calls nf90_get_var, nf90_inq_varid, nf90_open, nf90_create, nf90_def_dim, nf90_def_var, nf90_enddef, nf90_inq_dimid, nf90_inquire, nf90_inquire_dimension, nf90_put_att, nf90_sync
writestat_dims_nc calls nf90_inq_varid, nf90_inquire_dimension, nf90_put_var
alignment calls is_equal
nchandle_error calls nf90_strerror
udales calls execute_runmode_actions