exitmpi – uDALES
exitmpi Subroutine
10 statements
Source File
public subroutine exitmpi()
Uses
decomp_2d
Arguments
None
Calls
Called by
Source Code
  subroutine exitmpi
    use decomp_2d
    implicit none
    if(myid==0)then
      CPU_program = MPI_Wtime() - CPU_program0
      write(6,*)'TOTAL CPU time = ', CPU_program
    end if
    !call MPI_Comm_free( comm3d, mpierr )
    !call MPI_FINALIZE(mpierr)
    call decomp_2d_finalize
    call MPI_FINALIZE(mpierr)
  end subroutine exitmpi
Call graph
exitmpi calls decomp_2d_finalize, mpi_finalize, mpi_wtime
exitmodules calls exitmpi
dalesurban calls exitmpi