exitstat_nc – uDALES
exitstat_nc Subroutine
7 statements
Source File
public subroutine exitstat_nc(ncid)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: ncid
Calls
Called by
Source Code
  subroutine exitstat_nc(ncid)
   implicit none
   integer, intent(in) :: ncid
   integer status
   status = nf90_close(ncid)
   if (status /= nf90_noerr) call nchandle_error(status)
 end subroutine exitstat_nc
Call graph
exitstat_nc calls nf90_close, nchandle_error
nchandle_error calls nf90_strerror
exitfielddump calls exitstat_nc
dalesurban calls exitfielddump