fluidvolume – uDALES
fluidvolume Subroutine
17 statements
Source File
public subroutine fluidvolume(volume)
Uses
modglobal
modfields
modmpi
Arguments
Type Intent Optional Attributes Name
real, intent(out) :: volume
Called by
Contents
Source Code
fluidvolume
Source Code
  subroutine fluidvolume(volume)
    ! calculates fluid volume of domain excluding blocks
    use modglobal, only   : ib,ie,jb,je,kb,ke,dy,dxf,dzf
    use modfields, only   : IIc
    use modmpi, only      : sumy_ibm
    implicit none
    real, intent(out)             :: volume
    real, dimension(ib:ie,kb:ke)  :: sumy
    real, dimension(kb:ke)        :: sumxy
    integer                          k
    sumy = 0.
    sumxy = 0.
    ! integrate fluid volume in y
    call sumy_ibm(sumy,IIc(ib:ie,jb:je,kb:ke)*dy,ib,ie,jb,je,kb,ke,IIc(ib:ie,jb:je,kb:ke))
    ! integrate fluid area in x
    do k=kb,ke
      sumxy(k) = sum(sumy(ib:ie,k)*dxf(ib:ie))
    end do
    ! integrate fluid area in z
    volume = sum(sumxy(kb:ke)*dzf(kb:ke))
  end subroutine fluidvolume
Call graph
calcfluidvolumes calls fluidvolume
startup calls calcfluidvolumes
dalesurban calls startup