interp_velocity_c – uDALES
interp_velocity_c Function
9 statements
Source File
public function interp_velocity_c(i, j, k)
Uses
modfields
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: i
integer, intent(in) :: j
integer, intent(in) :: k
Return Value real, (3)
Called by
Source Code
   function interp_velocity_c(i, j, k)
     ! interpolates the velocity at c-grid location i,j,k
     use modfields, only :  u0, v0, w0
     real ::  interp_velocity_c(3)
     integer, intent(in) :: i, j, k
     interp_velocity_c(1) = 0.5 * (u0(i,j,k) + u0(i+1,j,k))
     interp_velocity_c(2) = 0.5 * (v0(i,j,k) + v0(i,j+1,k))
     interp_velocity_c(3) = 0.5 * (w0(i,j,k) + w0(i,j,k+1))
     return
   end function interp_velocity_c
Call graph
wallfunheat calls interp_velocity_c
ibmwallfun calls wallfunheat
dalesurban calls ibmwallfun