is_equal – uDALES
is_equal Function
10 statements
Source File
public function is_equal(a, b)
Uses
modglobal
Arguments
Type Intent Optional Attributes Name
real, intent(in), dimension(3) :: a
real, intent(in), dimension(3) :: b
Return Value logical
Called by
Source Code
   logical function is_equal(a,b)
     ! determines whether two vectors are equal to each other within a tolerance of eps1
     use modglobal, only : eps1
     implicit none
     real, dimension(3), intent(in) :: a, b
     if (all(abs(a - b) < eps1)) then
       is_equal = .true.
     else
       is_equal = .false.
     end if
   end function is_equal
Call graph
alignment calls is_equal
local_coords calls is_equal
wallfunheat calls is_equal, local_coords
wallfunmom calls is_equal, alignment, local_coords
ibmwallfun calls wallfunheat, wallfunmom
initibmwallfun calls alignment
initibm calls initibmwallfun
udales calls ibmwallfun, initibm, execute_runmode_actions
tests_mpi_operators calls initibm
tests_read_sparse_ijk calls initibm
execute_runmode_actions calls tests_mpi_operators, tests_read_sparse_ijk