local_coords – uDALES
local_coords Subroutine
15 statements
Source File
public subroutine local_coords(uvec, norm, span, strm, valid)
Uses
modglobal
Arguments
Type Intent Optional Attributes Name
real, intent(in), dimension(3) :: uvec
real, intent(in), dimension(3) :: norm
real, intent(out), dimension(3) :: span
real, intent(out), dimension(3) :: strm
logical, intent(out) :: valid
Calls
Called by
Source Code
   subroutine local_coords(uvec, norm, span, strm, valid)
     ! returns the local streamwise (strm) and spanwise vectors (span) in the
     ! plane normal to (norm) containing the velocity vector (uvec)
     use modglobal, only : vec0
     real, intent(in),  dimension(3) :: uvec, norm
     real, intent(out), dimension(3) :: span, strm
     logical, intent(out) :: valid
     span = cross_product(norm, uvec)
     !if (is_equal(span, (/0.,0.,0./))) then
     ! velocity is pointing into or outof the surface
     if (is_equal(span, vec0)) then
       strm = 0.
       valid = .false.
     else
       span = span / norm2(span)
       valid = .true.
     end if
     strm = cross_product(span, norm)
   end subroutine local_coords
Call graph
local_coords calls cross_product, is_equal
wallfunheat calls local_coords
wallfunmom calls local_coords
ibmwallfun calls wallfunheat, wallfunmom
dalesurban calls ibmwallfun