matinv4 – uDALES
matinv4 Function
22 statements
Source File
public pure function matinv4(A) result(B)
Arguments
Type Intent Optional Attributes Name
real, intent(in) :: A(4,4)
Return Value real, (4,4)
Called by
Call graph
eb calls matinv4
initeb calls matinv4
dalesurban calls eb, initeb