moist_flux – uDALES
moist_flux Function
4 statements
Source File
public function moist_flux(cveg, resa, qtair, qwall, hurel, resc, ress)
Arguments
Type Intent Optional Attributes Name
real, intent(in) :: cveg
real, intent(in) :: resa
real, intent(in) :: qtair
real, intent(in) :: qwall
real, intent(in) :: hurel
real, intent(in) :: resc
real, intent(in) :: ress
Return Value real
Called by
Source Code
   real function moist_flux(cveg, resa, qtair, qwall, hurel, resc, ress)
     real, intent(in) :: cveg, resa, qtair, qwall, hurel, resc, ress
     moist_flux = min(0., cveg * (qtair - qwall)         / (resa + resc) + &
                     (1 - cveg)* (qtair - qwall * hurel) / (resa + ress))
   end function moist_flux
Call graph
wallfunheat calls moist_flux
ibmwallfun calls wallfunheat
dalesurban calls ibmwallfun