nchandle_error – uDALES
nchandle_error Subroutine
10 statements
Source File
public subroutine nchandle_error(status)
Uses
netcdf
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: status
Calls
Called by
Source Code
  subroutine nchandle_error(status)
    use netcdf
    implicit none
    integer, intent(in) :: status
    if(status /= nf90_noerr) then
      write(0, *) trim(nf90_strerror(status))
      write(0, *) 'ERROR: status',  status
      stop 1
    end if
  end subroutine nchandle_error
Call graph
nchandle_error calls nf90_strerror
define_nc calls nchandle_error
exitstat_nc calls nchandle_error
exitfielddump calls exitstat_nc
initeb calls define_nc
initfielddump calls define_nc
initibm calls define_nc
initstatsdump calls define_nc
tests_mpi_operators calls initibm
tests_read_sparse_ijk calls initibm
udales calls exitfielddump, initeb, initfielddump, initibm, initstatsdump, execute_runmode_actions
execute_runmode_actions calls tests_mpi_operators, tests_read_sparse_ijk