ncinfo – uDALES
ncinfo Subroutine
9 statements
Source File
public subroutine ncinfo(out, in1, in2, in3, in4)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(out), dimension(4) :: out
character(len=*), intent(in) :: in1
character(len=*), intent(in) :: in2
character(len=*), intent(in) :: in3
character(len=*), intent(in) :: in4
Called by
Source Code
  subroutine ncinfo(out,in1,in2,in3,in4)
    implicit none
    character(*), dimension(4),intent(out) ::out
    character(*), intent(in) ::in1,in2,in3,in4
    out(1) = in1
    out(2) = in2
    out(3) = in3
    out(4) = in4
  end subroutine ncinfo
Call graph
initeb calls ncinfo
initfielddump calls ncinfo
initibm calls ncinfo
initstatsdump calls ncinfo
tests_mpi_operators calls initibm
tests_read_sparse_ijk calls initibm
udales calls initeb, initfielddump, initibm, initstatsdump, execute_runmode_actions
execute_runmode_actions calls tests_mpi_operators, tests_read_sparse_ijk