qsat – uDALES
qsat Function
7 statements
Source File
public function qsat(T)
Arguments
Type Intent Optional Attributes Name
real, intent(in) :: T
Return Value real
Called by
Source Code
      real function qsat(T)
         implicit none
         real, intent(in) :: T
         real :: gres
         gres = 611.00*exp(17.27*(T - 273.15)/(T - 35.85)) ![Pa] Bolton 1980
         qsat = 0.62198*0.01*gres/(1000-0.01*gres) ![kg/kg] Murphy & Koop 2005 !1000 can be replaced with actual air pressure if desired
      end function qsat
Call graph
readfacetfiles calls qsat
updategr calls qsat
eb calls updategr
tests_mpi_operators calls readfacetfiles
tests_read_sparse_ijk calls readfacetfiles
udales calls readfacetfiles, eb, execute_runmode_actions
execute_runmode_actions calls tests_mpi_operators, tests_read_sparse_ijk