subgrid – uDALES
subgrid Subroutine
17 statements
Source File
public subroutine subgrid()
Uses
modfields
modglobal
Arguments
None
Calls
Called by
Call graph
subgrid calls closure, diffc, diffe, diffu, diffv, diffw, sources
closure calls closurebc
closurebc calls exchange_halo_z, reassure_fluxtop_boundary
reassure_fluxtop_boundary calls fluxtop, fluxtopscal
udales calls subgrid