timedepsw – uDALES
timedepsw Subroutine
22 statements
Source File
private subroutine timedepsw()
Uses
initfac
modmpi
modglobal
Arguments
None
Called by
Source Code
  subroutine timedepsw
    use modglobal, only : timee, nfcts, rk3step, tnextEB
    use initfac, only : netsw
    use modmpi, only : myid
    implicit none
    integer t,n
    real fac
    if(.not.(ltimedepsw .and. myid==0)) return
    if ((rk3step .eq. 3) .and. (timee .ge. tnextEB)) then
    ! if (myid == 0) then
    !  write(*,*) "EB coming up so changing solar position"
    ! end if
    !---- interpolate ----
    do t=ntimedepsw,1,-1
      if (timee .ge. timesw(t)) then
        exit
      endif
    end do
    if (t .ne. ntimedepsw) then
      fac = (timee - timesw(t)) / (timesw(t+1) - timesw(t))
      do n=1,nfcts
         netsw(n) = netswt(n,t) + fac * (netswt(n,t+1) - netswt(n,t))
      end do
    end if
    end if
  end subroutine timedepsw
Call graph
timedep calls timedepsw
inittimedep calls timedep
dalesurban calls timedep, inittimedep