timedep – uDALES
timedep Subroutine
8 statements
Source File
public subroutine timedep()
Arguments
None
Calls
Called by
Source Code
  subroutine timedep
!-----------------------------------------------------------------|
!                                                                 |
!*** *timedep*  calculates ls forcings and surface forcings       |
!               case as a funtion of timee                        |
!                                                                 |
!      Roel Neggers    K.N.M.I.     01/05/2001                    |
!                                                                 |
!                                                                 |
!    calls                                                        |
!    * timedepz                                                   |
!      calculation of large scale advection, radiation and        |
!      surface fluxes by interpolation between prescribed         |
!      values at certain times                                    |
!                                                                 |
!    * timedepsurf                                                |
!      calculation  surface fluxes by interpolation               |
!      between prescribed values at certain times                 |
!                                                                 |
!                                                                 |
!-----------------------------------------------------------------|
    implicit none
    if (.not. ltimedep) return
    call timedepsurf
    call timedepnudge
    call timedeplw
    call timedepsw
  end subroutine timedep
Call graph
timedep calls timedeplw, timedepnudge, timedepsurf, timedepsw
inittimedep calls timedep
dalesurban calls timedep, inittimedep