voutletarea – uDALES
voutletarea Subroutine
15 statements
Source File
public subroutine voutletarea(area)
Uses
modmpi
modfields
modglobal
Arguments
Type Intent Optional Attributes Name
real, intent(out) :: area
Calls
Called by
Source Code
  subroutine voutletarea(area)
    ! calculates outlet area of domain for v-velocity excluding blocks
    use modglobal, only : ib,ie,jb,je,kb,ke,dxf,dzf,jerank
    use modfields, only : IIc
    use modmpi,    only : sumx_ibm
    implicit none
    real, intent(out)       :: area
    real, dimension(kb:ke)  :: sumx
    integer                    k
    sumx = 0.
    ! integrate fluid area at outflow plane in x
    ! Assumes je=jtot
    call sumx_ibm(sumx,IIc(ib:ie,je,kb:ke)*dxf(1),ib,ie,je,je,kb,ke,IIc(ib:ie,je,kb:ke))
    ! integrate fluid area at outflow plane in z
    do k=kb,ke
      sumx(k) = sumx(k)*dzf(k)
    end do
    area = sum(sumx(kb:ke))
  end subroutine voutletarea
Call graph
voutletarea calls sumx_ibm
sumx_ibm calls mpi_allreduce
calcfluidvolumes calls voutletarea
dalesurban calls calcfluidvolumes