writestat_time_nc – uDALES
writestat_time_nc Subroutine
17 statements
Source File
public subroutine writestat_time_nc(ncid, nvar, ncname, vars, nrec, lraise)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: ncid
integer, intent(in) :: nvar
character(len=*), intent(in), dimension(:,:) :: ncname
real, intent(in), dimension(nvar) :: vars
integer, intent(inout) :: nrec
logical, intent(in) :: lraise
Calls
Called by
Source Code
  subroutine writestat_time_nc(ncid,nvar,ncname,vars,nrec,lraise)
    implicit none
    integer, intent(in)                      :: ncid,nvar
    integer, intent(inout)                   :: nrec
    real,dimension(nvar),intent(in)          :: vars
    character(*), dimension(:,:),intent(in)  :: ncname
    logical, intent(in)                      :: lraise
    integer :: iret,n,varid
    !write(*,*) 'time-nc'
    if(lraise) then
      nrec = nrec+1
    end if
    do n=1,nvar
       iret = nf90_inq_varid(ncid, ncname(n,1), VarID)
       iret = nf90_put_var(ncid, VarID, vars(n), start=(/nrec/))
    end do
    iret = nf90_sync(ncid)
  end subroutine writestat_time_nc
Call graph
writestat_time_nc calls nf90_inq_varid, nf90_put_var, nf90_sync
writestat_nc calls writestat_time_nc
eb calls writestat_nc
fielddump calls writestat_nc
ibmwallfun calls writestat_nc
statsdump calls writestat_nc
dalesurban calls eb, fielddump, ibmwallfun, statsdump