writestat_1D_nc – uDALES
writestat_1D_nc Subroutine
13 statements
Source File
public subroutine writestat_1D_nc(ncid, nvar, ncname, vars, nrec, dim1)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: ncid
integer, intent(in) :: nvar
character(len=*), intent(in), dimension(:,:) :: ncname
real, intent(in), dimension(dim1,nvar) :: vars
integer, intent(in) :: nrec
integer, intent(in) :: dim1
Calls
Called by
Source Code
  subroutine writestat_1D_nc(ncid,nvar,ncname,vars,nrec,dim1)
    implicit none
    integer, intent(in)                      :: ncid,nvar,dim1
    integer, intent(in)                      :: nrec
    real,dimension(dim1,nvar),intent(in)     :: vars
    character(*), dimension(:,:),intent(in)  :: ncname
    integer :: iret,n,varid
    do n=1,nvar
      iret = nf90_inq_varid(ncid, ncname(n,1), VarID)
      iret = nf90_put_var(ncid, VarID, vars(1:dim1,n),(/1,nrec/),(/dim1,1/))
    end do
    iret = nf90_sync(ncid)
  end subroutine writestat_1D_nc
Call graph
writestat_1d_nc calls nf90_inq_varid, nf90_put_var, nf90_sync
writestat_nc calls writestat_1d_nc
eb calls writestat_1d_nc, writestat_nc
ibmwallfun calls writestat_1d_nc, writestat_nc
statsdump calls writestat_1d_nc, writestat_nc
fielddump calls writestat_nc
dalesurban calls eb, ibmwallfun, statsdump, fielddump