writestat_3D_short_nc – uDALES
writestat_3D_short_nc Subroutine
13 statements
Source File
public subroutine writestat_3D_short_nc(ncid, nvar, ncname, vars, nrec, dim1, dim2, dim3)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: ncid
integer, intent(in) :: nvar
character(len=*), intent(in), dimension(:,:) :: ncname
integer(kind=selected_int_kind(4)), intent(in), dimension(dim1,dim2,dim3,nvar) :: vars
integer, intent(in) :: nrec
integer, intent(in) :: dim1
integer, intent(in) :: dim2
integer, intent(in) :: dim3
Calls
Called by
Contents
Source Code
writestat_3D_short_nc
Source Code
  subroutine writestat_3D_short_nc(ncid,nvar,ncname,vars,nrec,dim1,dim2,dim3)
    implicit none
    integer, intent(in)                      :: ncid,nvar,dim1,dim2,dim3
    integer, intent(in)                      :: nrec
    integer(KIND=selected_int_kind(4)),dimension(dim1,dim2,dim3,nvar),intent(in)       :: vars
    character(*), dimension(:,:),intent(in)  :: ncname
    integer :: iret,n,varid
    !write(*,*) '3Dnc short'
    do n=1,nvar
      iret = nf90_inq_varid(ncid, ncname(n,1), VarID)
      iret = nf90_put_var(ncid, VarID, vars(1:dim1,1:dim2,1:dim3,n),(/1,1,1,nrec/),(/dim1,dim2,dim3,1/))
    end do
    iret = nf90_sync(ncid)
  end subroutine writestat_3D_short_nc
Call graph
writestat_3d_short_nc calls nf90_sync, nf90_put_var, nf90_inq_varid
writestat_nc calls writestat_3d_short_nc
statsdump calls writestat_nc
eb calls writestat_nc
fielddump calls writestat_nc
dalesurban calls statsdump, eb, fielddump