writestat_2D_nc – uDALES
writestat_2D_nc Subroutine
13 statements
Source File
public subroutine writestat_2D_nc(ncid, nvar, ncname, vars, nrec, dim1, dim2)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: ncid
integer, intent(in) :: nvar
character(len=*), intent(in), dimension(:,:) :: ncname
real, intent(in), dimension(:,:,:) :: vars
integer, intent(in) :: nrec
integer, intent(in) :: dim1
integer, intent(in) :: dim2
Calls
Called by
Contents
Source Code
writestat_2D_nc
Source Code
  subroutine writestat_2D_nc(ncid,nvar,ncname,vars,nrec,dim1,dim2)
    implicit none
    integer, intent(in)                      :: ncid,nvar,dim1,dim2
    integer, intent(in)                      :: nrec
    real,dimension(:,:,:),intent(in)         :: vars
    character(*), dimension(:,:),intent(in)  :: ncname
    integer :: iret,n,varid
    do n=1,nvar
      iret = nf90_inq_varid(ncid, ncname(n,1), VarID)
      iret = nf90_put_var(ncid, VarID, vars(1:dim1,1:dim2,n),(/1,1,nrec/),(/dim1,dim2,1/))
    end do
    iret = nf90_sync(ncid)
  end subroutine writestat_2D_nc
Call graph
writestat_2d_nc calls nf90_sync, nf90_put_var, nf90_inq_varid
writestat_nc calls writestat_2d_nc
eb calls writestat_2d_nc, writestat_nc
statsdump calls writestat_nc
dalesurban calls eb, statsdump, fielddump
fielddump calls writestat_nc