xs_periodic – uDALES
xs_periodic Subroutine
12 statements
Source File
public subroutine xs_periodic()
Uses
modfields
modglobal
Arguments
None
Called by
Source Code
   subroutine xs_periodic
      use modglobal, only : ib, ie, ihc
      use modfields, only : sv0, svm
      integer m, n
      do m = 1, ihc
         sv0(ib - m, :, :, :) = sv0(ie + 1 - m, :, :, :)
         sv0(ie + m, :, :, :) = sv0(ib - 1 + m, :, :, :)
         svm(ib - m, :, :, :) = svm(ie + 1 - m, :, :, :)
         svm(ie + m, :, :, :) = svm(ib - 1 + m, :, :, :)
      end do
      return
   end subroutine xs_periodic
Call graph
halos calls xs_periodic
readinitfiles calls halos
dalesurban calls halos, readinitfiles