yinterpolate – uDALES
yinterpolate Subroutine
11 statements
Source File
public subroutine yinterpolate(input, output, ks, kf)
Uses
modglobal
Arguments
Type Intent Optional Attributes Name
real, intent(in), dimension(jbdum:jedum,ks:kf,1:nstore) :: input
real, intent(inout), dimension(jb :je ,ks:kf,1:nstore) :: output
integer, intent(in) :: ks
integer, intent(in) :: kf
Called by
Contents
Source Code
yinterpolate
Source Code
  subroutine yinterpolate(input,output,ks,kf)
  use modglobal, only : jb,je, nstore
  integer, intent(in) :: ks
  integer, intent(in) :: kf
  real, dimension(jbdum:jedum,ks:kf,1:nstore), intent(in)  :: input
  real, dimension(jb   :je   ,ks:kf,1:nstore), intent(inout) :: output
  integer j
    do j=jb,je
!      if (np==0 .and. yloclowf(j)==)
      output(j,:,:) = input(yloclowf(j),:,:) + (input(ylocupf(j),:,:) - input(yloclowf(j),:,:)) / (yfdum(ylocupf(j)) - yfdum(yloclowf(j))) * (yf(j) - yfdum(yloclowf(j)))
    end do
  end subroutine yinterpolate
Call graph
readinletfile calls yinterpolate
inletgennotemp calls readinletfile
readinitfiles calls readinletfile, boundary
inletgen calls readinletfile
startup calls readinitfiles
boundary calls inletgennotemp, inletgen
dalesurban calls startup, boundary