zinterpolatew1d – uDALES
zinterpolatew1d Subroutine
19 statements
Source File
public subroutine zinterpolatew1d(input, output)
Uses
modglobal
Arguments
Type Intent Optional Attributes Name
real, intent(in), dimension(kbin:kein+1) :: input
real, intent(inout), dimension(kb:ke+1) :: output
Called by
Contents
Source Code
zinterpolatew1d
Source Code
  subroutine zinterpolatew1d(input,output)
  use modglobal,      only : kb,ke,zh
  implicit none
  real, dimension(kbin:kein+1), intent(in)  :: input
  real, dimension(kb:ke+1), intent(inout) :: output
  integer k
     do k=kb,ke+1
      if (linuh(k) == kein+2) then      ! indicator for extrapolation!
        output(k) = input(kein+1)
      elseif (linlh(k) == kbin-1) then ! interprets this as extrapolation to bottom (use u=0 at z+=0)
        output(k) = input(kbin) !=0
!        output(k) = input(kbin)/zhin(kbin) * zh(k)
!        output(:,k,:) = input(:,kbin,:)   ! temeperature is not zero at the wall, so line above is wrong
      else                            ! normal interpolation
        output(k) = input(linlh(k)) + (input(linuh(k)) - input(linlh(k))) / (zhin(linuh(k)) - zhin(linlh(k))) * (zh(k) - zh(linlh(k)))
        if ((zh(k) .gt. zhin(linuh(k))) .or. (zh(k) .lt. zhin(linlh(k)))) then
          write(6,*) '!!!Mistake in zinterpolatew1d !!!!'
        end if
      end if
    end do
  end subroutine zinterpolatew1d
Call graph
readrestartfiles calls zinterpolatew1d
readinitfiles calls readrestartfiles
startup calls readinitfiles
dalesurban calls startup