"""Generate MATLAB reference data for offline udgeom unit tests.

This tool writes a small set of deterministic STL fixtures and runs the MATLAB
`udgeom` class on them once. The resulting JSON references are committed so the
Python unit tests can compare directly against MATLAB behavior without
requiring MATLAB at test time.
"""

import argparse
import json
import shutil
import subprocess
from pathlib import Path
from typing import Dict

import numpy as np
import trimesh


REPO_ROOT = Path(__file__).resolve().parents[1]
DATA_DIR = REPO_ROOT / "tools" / "python" / "tests" / "data" / "udgeom_matlab"
MATLAB_HELPER = REPO_ROOT / "tools" / "matlab" / "harvest_udgeom_reference.m"


def _scene_single_box() -> trimesh.Trimesh:
    mesh = trimesh.creation.box(extents=(2.0, 3.0, 4.0))
    mesh.apply_translation((1.0, 1.5, 2.0))
    return mesh


def _scene_two_boxes_with_ground() -> trimesh.Trimesh:
    box_a = trimesh.creation.box(extents=(2.0, 2.0, 3.0))
    box_a.apply_translation((1.0, 1.0, 1.5))

    box_b = trimesh.creation.box(extents=(1.5, 2.5, 2.0))
    box_b.apply_translation((5.0, 4.0, 1.0))

    ground_vertices = np.array(
        [
            [-1.0, -1.0, 0.0],
            [7.0, -1.0, 0.0],
            [7.0, 6.0, 0.0],
            [-1.0, 6.0, 0.0],
        ],
        dtype=float,
    )
    ground_faces = np.array([[0, 1, 2], [0, 2, 3]], dtype=int)
    ground = trimesh.Trimesh(vertices=ground_vertices, faces=ground_faces, process=False)

    scene = trimesh.util.concatenate([ground, box_a, box_b])
    scene.process(validate=True)
    return scene


def _fixture_meshes() -> Dict[str, trimesh.Trimesh]:
    flat_ground = trimesh.load_mesh(str(REPO_ROOT / "examples" / "001" / "flat_ground.stl"))
    xie_castro = trimesh.load_mesh(str(REPO_ROOT / "tests" / "cases" / "100" / "xie_castro_2008_STL.stl"))
    return {
        "flat_ground": flat_ground,
        "single_box": _scene_single_box(),
        "two_boxes_with_ground": _scene_two_boxes_with_ground(),
        "xie_castro_2008": xie_castro,
    }


def _write_ascii_stl(mesh: trimesh.Trimesh, path: Path) -> None:
    path.write_text(mesh.export(file_type="stl_ascii"))


def _run_matlab_harvest(stl_path: Path, json_path: Path) -> None:
    helper_dir = MATLAB_HELPER.parent
    command = (
        f"addpath('{helper_dir.as_posix()}'); "
        f"harvest_udgeom_reference('{stl_path.as_posix()}','{json_path.as_posix()}');"
    )
    subprocess.run(
        ["matlab", "-batch", command],
        check=True,
        cwd=REPO_ROOT,
    )


def _write_manifest(fixtures) -> None:
    manifest = {
        "fixtures": fixtures,
        "note": (
            "Generated by tools/harvest_udgeom_matlab_references.py. "
            "Normal Python unit tests consume these committed files and do not "
            "require MATLAB."
        ),
    }
    (DATA_DIR / "manifest.json").write_text(json.dumps(manifest, indent=2) + "\n")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--clean",
        action="store_true",
        help="Remove the existing reference directory before regenerating.",
    )
    args = parser.parse_args()

    if shutil.which("matlab") is None:
        raise SystemExit("matlab is required to harvest udgeom references")

    if args.clean and DATA_DIR.exists():
        shutil.rmtree(DATA_DIR)
    DATA_DIR.mkdir(parents=True, exist_ok=True)

    fixtures = _fixture_meshes()
    for name, mesh in fixtures.items():
        stl_path = DATA_DIR / f"{name}.stl"
        json_path = DATA_DIR / f"{name}.json"
        _write_ascii_stl(mesh, stl_path)
        _run_matlab_harvest(stl_path, json_path)

    _write_manifest(sorted(fixtures))
    print(f"Wrote udgeom MATLAB references to {DATA_DIR}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
