"""Generate MATLAB reference data for offline udbase integration tests."""

import argparse
import json
import shutil
import subprocess
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
DATA_DIR = REPO_ROOT / "tests" / "integration" / "udbase_against_matlab" / "data"
MATLAB_HELPER = REPO_ROOT / "tests" / "integration" / "udbase_against_matlab" / "harvest_udbase_reference.m"
DEFAULT_CASES = ("064", "101")


def _run_matlab_harvest(case_dir: Path, json_path: Path) -> None:
    helper_dir = MATLAB_HELPER.parent
    command = (
        f"addpath('{helper_dir.as_posix()}'); "
        f"harvest_udbase_reference('{case_dir.as_posix()}','{json_path.as_posix()}');"
    )
    subprocess.run(
        ["matlab", "-batch", command],
        check=True,
        cwd=REPO_ROOT,
    )


def _write_manifest(cases: list[str]) -> None:
    manifest = {
        "cases": cases,
        "note": (
            "Generated by tools/harvest_udbase_matlab_references.py. "
            "Normal Python integration tests consume these committed files and do not "
            "require MATLAB."
        ),
    }
    (DATA_DIR / "manifest.json").write_text(json.dumps(manifest, indent=2) + "\n")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--clean",
        action="store_true",
        help="Remove the existing reference directory before regenerating.",
    )
    parser.add_argument(
        "--cases",
        nargs="+",
        default=list(DEFAULT_CASES),
        help="Case identifiers under tests/cases to harvest.",
    )
    args = parser.parse_args()

    if shutil.which("matlab") is None:
        raise SystemExit("matlab is required to harvest udbase references")

    if args.clean and DATA_DIR.exists():
        shutil.rmtree(DATA_DIR)
    DATA_DIR.mkdir(parents=True, exist_ok=True)

    case_ids = [f"{int(case):03d}" for case in args.cases]
    for case_id in case_ids:
        case_dir = REPO_ROOT / "tests" / "cases" / case_id
        if not case_dir.is_dir():
            raise SystemExit(f"Missing case directory: {case_dir}")
        json_path = DATA_DIR / f"{case_id}.json"
        _run_matlab_harvest(case_dir, json_path)

    _write_manifest(case_ids)
    print(f"Wrote udbase MATLAB references to {DATA_DIR}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
