#!/bin/bash
#
#SBATCH --nodes=1
#SBATCH --tasks-per-node=1
#SBATCH --cpus-per-task=1
#SBATCH --job-name=job_gather_out1d
#SBATCH --account=n02-ASSURE
#SBATCH --partition=serial
#SBATCH --qos=serial
#SBATCH --time=24:00:0
#SBATCH --mem=125G

export OMP_NUM_THREADS=1

module load cray-python/3.9.13.1

python -m pip install --user xarray netCDF4

# python checknc.py
python -u gather_out1d.py 797 ./797 ./797

