!> \file nesting_prolong.f90
!!  Conservative prolongation of parent boundary bands onto the child grid.
!!
!!  THE SPECIFICATION IS THE PYTHON.  This is a port of
!!  udprep.nesting.conservative_interpolate; that implementation, its 100+
!!  unit tests and docs/udales-nesting-spec.md define the numerics, and
!!  runmode TEST_NESTING_PROLONG cross-checks this code against reference
!!  output generated by it.  Any disagreement is a bug here.
!!
!!  WHY IN THE SOLVER.  Until now the writer prolonged offline and stored
!!  child-grid slabs, which for a refinement ratio r costs r^3 times the
!!  parent's band volume, in double precision -- 16x at r = 2 and 128x at
!!  r = 4.  Prolonging here instead lets the file carry raw parent-grid bands
!!  in single precision.  It is sound because the prolongation is conservative:
!!  child face fluxes summed over a parent face equal the parent face flux to
!!  round-off (test_nesting.py TestP2FluxIdentity), so a band whose net flux
!!  was zeroed on the PARENT grid still has zero net flux after prolongation.
!!  The per-level correction therefore stays a single f8 scalar in the header
!!  and precision costs nothing.
!!
!!  STRUCTURE.  Three separable 1-D operators, one per axis:
!!
!!    tangential axis (the component is cell centred on it)
!!        out(i) = f(idx(i)) + slope(idx(i)) * (target(i) - centre(idx(i)))
!!      with idx the parent cell containing the target and slope a central
!!      difference, one sided at the ends and mask aware (a solid neighbour is
!!      not used, so an IBM parent's in-building velocity cannot leak into the
!!      fluid cell beside it).  The slope term is dropped for prolongation
!!      "constant".
!!
!!    normal axis (the component is face staggered on it)
!!        out(i) = f(idx(i)) * wlo(i) + f(idx(i)+1) * (1 - wlo(i))
!!      with wlo snapped to exactly 1 or 0 when the target coincides with a
!!      parent face.  That snap is what makes the flux identity exact.
!!
!!  Tangential axes are applied before the normal axis so that the parent mask
!!  is still on the parent stagger while the slopes need it; the operators act
!!  on different axes, so the result is independent of their order.
!!
!!  \author Maarten van Reeuwijk, Imperial College London
!
!  This file is part of uDALES.
!
! uDALES is free software; you can redistribute it and/or modify
! it under the terms of the GNU General Public License as published by
! the Free Software Foundation; either version 3 of the License, or
! (at your option) any later version.
!
! uDALES is distributed in the hope that it will be useful,
! but WITHOUT ANY WARRANTY; without even the implied warranty of
! MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
! GNU General Public License for more details.
!
! You should have received a copy of the GNU General Public License
! along with this program.  If not, see <http://www.gnu.org/licenses/>.
!
! Copyright (C) 2016- the uDALES Team, Imperial College London.
!
module nesting_prolong
   implicit none
   private
   public :: prolong_axis_map, build_tangential_map, build_normal_map, &
             prolong_band, prolong_free, PROLONG_CONSTANT, PROLONG_LINEAR

   integer, parameter :: PROLONG_CONSTANT = 1
   integer, parameter :: PROLONG_LINEAR   = 2

   !> Relative tolerance for "this target sits on a parent face", scaled by the
   !! smallest parent spacing.  Mirrors udprep.nesting._ALIGN_RTOL.
   real, parameter :: ALIGN_RTOL = 1.e-9

   !> One axis of the map from parent indices to child indices.
   type prolong_axis_map
      logical              :: lnormal = .false. !< normal (linear) vs tangential
      integer              :: nc = 0            !< number of child points
      integer, allocatable :: idx(:)            !< parent index, 1-based
      real,    allocatable :: w(:)              !< normal: wlo; tangential: offset
   end type prolong_axis_map

contains

   !> Index of the last parent face at or below `t`, 1-based, clamped so that
   !! `idx` and `idx+1` are both valid faces.  Bisection: the vertical parent
   !! grid is stretched, so the spacing cannot be assumed uniform.
   integer function face_below(faces, t)
      real, intent(in) :: faces(:), t
      integer :: lo, hi, mid
      lo = 1; hi = size(faces)
      do while (hi - lo > 1)
         mid = (lo + hi)/2
         if (faces(mid) <= t) then
            lo = mid
         else
            hi = mid
         end if
      end do
      face_below = min(max(lo, 1), size(faces) - 1)
   end function face_below

   !> Piecewise-constant map: which parent cell contains each target.
   subroutine build_tangential_map(faces, centres, target, map, ierr)
      real, intent(in)  :: faces(:), centres(:), target(:)
      type(prolong_axis_map), intent(out) :: map
      integer, intent(out) :: ierr
      integer :: i
      real    :: tol

      ierr = 0
      tol = ALIGN_RTOL*minval(faces(2:) - faces(:size(faces)-1))
      if (minval(target) < faces(1) - tol .or. &
          maxval(target) > faces(size(faces)) + tol) then
         ierr = 1
         return
      end if
      map%lnormal = .false.
      map%nc = size(target)
      allocate(map%idx(map%nc), map%w(map%nc))
      do i = 1, map%nc
         map%idx(i) = face_below(faces, target(i))
         map%w(i)   = target(i) - centres(map%idx(i))
      end do
   end subroutine build_tangential_map

   !> Linear map along the face-normal axis, with the on-face snap.
   subroutine build_normal_map(faces, target, map, ierr)
      real, intent(in)  :: faces(:), target(:)
      type(prolong_axis_map), intent(out) :: map
      integer, intent(out) :: ierr
      integer :: i, k
      real    :: tol, lo, hi

      ierr = 0
      tol = ALIGN_RTOL*minval(faces(2:) - faces(:size(faces)-1))
      if (minval(target) < faces(1) - tol .or. &
          maxval(target) > faces(size(faces)) + tol) then
         ierr = 1
         return
      end if
      map%lnormal = .true.
      map%nc = size(target)
      allocate(map%idx(map%nc), map%w(map%nc))
      do i = 1, map%nc
         k = face_below(faces, target(i))
         lo = faces(k); hi = faces(k + 1)
         map%idx(i) = k
         map%w(i)   = (hi - target(i))/(hi - lo)
         ! Snap so a child face coincident with a parent face reproduces the
         ! parent value bit for bit; the flux identity depends on it.
         if (abs(target(i) - lo) <= tol) map%w(i) = 1.
         if (abs(target(i) - hi) <= tol) map%w(i) = 0.
      end do
   end subroutine build_normal_map

   subroutine prolong_free(map)
      type(prolong_axis_map), intent(inout) :: map
      if (allocated(map%idx)) deallocate(map%idx)
      if (allocated(map%w))   deallocate(map%w)
      map%nc = 0
   end subroutine prolong_free

   !> Per-parent-cell slope along axis 1 of a 3-D array, mask aware.
   !! Central where both neighbours are usable, one sided at the ends and
   !! beside a solid, zero between two solids and inside a solid.
   subroutine slopes_axis1(f, centres, mask, lmask, s)
      real,    intent(in)  :: f(:,:,:), centres(:)
      logical, intent(in)  :: mask(:,:,:), lmask
      real,    intent(out) :: s(:,:,:)
      integer :: n, i, j, k, il, ir
      logical :: left, right

      n = size(f, 1)
      s = 0.
      if (n < 2) return
      do k = 1, size(f, 3)
         do j = 1, size(f, 2)
            do i = 1, n
               ! Neighbour indices clamped to the array: `il`/`ir` are only
               ! dereferenced when `left`/`right` say the neighbour exists.
               ! (Written this way, rather than f(i-1)/f(i+1) inside the guards,
               ! because gfortran >= 13 flags the guarded literal subscripts with
               ! -Wdo-subscript and the warning gate is zero-tolerance.)
               il = max(i - 1, 1)
               ir = min(i + 1, n)
               left  = (i > 1)
               right = (i < n)
               if (lmask) then
                  if (left)  left  = mask(il,j,k)
                  if (right) right = mask(ir,j,k)
               end if
               if (left .and. right) then
                  s(i,j,k) = (f(ir,j,k) - f(il,j,k))/(centres(ir) - centres(il))
               else if (left) then
                  s(i,j,k) = (f(i,j,k) - f(il,j,k))/(centres(i) - centres(il))
               else if (right) then
                  s(i,j,k) = (f(ir,j,k) - f(i,j,k))/(centres(ir) - centres(i))
               else
                  s(i,j,k) = 0.
               end if
               ! With two cells the single forward difference is the slope at
               ! both ends, which the branches above already give.
               if (lmask) then
                  if (.not. mask(i,j,k)) s(i,j,k) = 0.
               end if
            end do
         end do
      end do
   end subroutine slopes_axis1

   !> Apply one axis operator along axis 1, mapping (np,n2,n3) -> (nc,n2,n3).
   subroutine apply_axis1(f, map, scheme, centres, mask, lmask, out)
      real,    intent(in)  :: f(:,:,:), centres(:)
      type(prolong_axis_map), intent(in) :: map
      integer, intent(in)  :: scheme
      logical, intent(in)  :: mask(:,:,:), lmask
      real,    intent(out) :: out(:,:,:)
      real, allocatable    :: s(:,:,:)
      integer :: i, j, k, p

      if (map%lnormal) then
         do k = 1, size(f, 3)
            do j = 1, size(f, 2)
               do i = 1, map%nc
                  p = map%idx(i)
                  out(i,j,k) = f(p,j,k)*map%w(i) + f(p+1,j,k)*(1. - map%w(i))
               end do
            end do
         end do
      else
         if (scheme == PROLONG_LINEAR) then
            allocate(s(size(f,1), size(f,2), size(f,3)))
            call slopes_axis1(f, centres, mask, lmask, s)
         end if
         do k = 1, size(f, 3)
            do j = 1, size(f, 2)
               do i = 1, map%nc
                  p = map%idx(i)
                  out(i,j,k) = f(p,j,k)
                  if (scheme == PROLONG_LINEAR) out(i,j,k) = out(i,j,k) + s(p,j,k)*map%w(i)
               end do
            end do
         end do
         if (allocated(s)) deallocate(s)
      end if
   end subroutine apply_axis1

   !> Cyclic permutation (1,2,3) -> (2,3,1) of a 3-D array.
   subroutine rotate(f, g)
      real, intent(in)  :: f(:,:,:)
      real, intent(out) :: g(:,:,:)
      integer :: i, j, k
      do k = 1, size(f, 3)
         do j = 1, size(f, 2)
            do i = 1, size(f, 1)
               g(j,k,i) = f(i,j,k)
            end do
         end do
      end do
   end subroutine rotate

   subroutine rotate_l(f, g)
      logical, intent(in)  :: f(:,:,:)
      logical, intent(out) :: g(:,:,:)
      integer :: i, j, k
      do k = 1, size(f, 3)
         do j = 1, size(f, 2)
            do i = 1, size(f, 1)
               g(j,k,i) = f(i,j,k)
            end do
         end do
      end do
   end subroutine rotate_l

   !> Prolong one parent band component onto the child target grid.
   !!
   !! `f` is the parent field at this component's stagger; `mapx/y/z` are the
   !! per-axis maps from build_*_map, each already the right kind for this
   !! component (normal on the component's own axis, tangential on the other
   !! two).  `cx/cy/cz` are the parent CENTRE coordinates per axis, used by the
   !! linear slopes on tangential axes.  `mask` is the parent fluid mask at the
   !! same stagger (`lmask = .false.` to ignore it).
   !!
   !! Each axis is brought to position 1 by cyclic rotation, operated on, and
   !! rotated on; after three rotations the array is back in (x,y,z) order.
   !! Tangential axes are done first, and the mask is carried through the same
   !! rotations and remapped with the field, exactly as the Python does.
   subroutine prolong_band(f, mapx, mapy, mapz, cx, cy, cz, scheme, &
                           mask, lmask, out, ierr)
      real,    intent(in)  :: f(:,:,:)
      type(prolong_axis_map), intent(in) :: mapx, mapy, mapz
      real,    intent(in)  :: cx(:), cy(:), cz(:)
      integer, intent(in)  :: scheme
      logical, intent(in)  :: mask(:,:,:), lmask
      real,    intent(out) :: out(:,:,:)
      integer, intent(out) :: ierr

      type(prolong_axis_map) :: m(3)
      real,    allocatable :: a(:,:,:), b(:,:,:), rc(:)
      logical, allocatable :: ma(:,:,:), mb(:,:,:)
      integer :: pass, n1, n2, n3, nc
      logical :: want_tangential

      ierr = 0
      m(1) = mapx; m(2) = mapy; m(3) = mapz
      allocate(a(size(f,1), size(f,2), size(f,3))); a = f
      allocate(ma(size(mask,1), size(mask,2), size(mask,3))); ma = mask

      ! two sweeps: tangential axes first, then the normal one
      do pass = 1, 2
         want_tangential = (pass == 1)
         do n1 = 1, 3
            ! axis currently at position 1 is m(mod(n1 + shift)) -- track by
            ! rotating the map list alongside the data below
            if (m(1)%lnormal .neqv. want_tangential) then
               ! operate on axis 1
               nc = m(1)%nc
               if (allocated(rc)) deallocate(rc)
               select case (n1)
               case (1); allocate(rc(size(cx))); rc = cx
               case (2); allocate(rc(size(cy))); rc = cy
               case (3); allocate(rc(size(cz))); rc = cz
               end select
               allocate(b(nc, size(a,2), size(a,3)))
               call apply_axis1(a, m(1), scheme, rc, ma, lmask, b)
               deallocate(a); allocate(a(nc, size(b,2), size(b,3))); a = b
               deallocate(b)
               if (lmask) then
                  allocate(mb(nc, size(ma,2), size(ma,3)))
                  call remap_mask1(ma, m(1), mb)
                  deallocate(ma); allocate(ma(nc, size(mb,2), size(mb,3))); ma = mb
                  deallocate(mb)
               end if
            end if
            ! rotate data, mask and map list so the next axis is at position 1
            n2 = size(a,2); n3 = size(a,3)
            allocate(b(n2, n3, size(a,1))); call rotate(a, b)
            deallocate(a); allocate(a(n2, n3, size(b,3))); a = b; deallocate(b)
            if (lmask) then
               allocate(mb(size(ma,2), size(ma,3), size(ma,1))); call rotate_l(ma, mb)
               deallocate(ma); allocate(ma(size(mb,1), size(mb,2), size(mb,3)))
               ma = mb; deallocate(mb)
            end if
            m = m((/ 2, 3, 1 /))
         end do
      end do

      if (size(a,1) /= size(out,1) .or. size(a,2) /= size(out,2) .or. &
          size(a,3) /= size(out,3)) then
         ierr = 2
      else
         out = a
      end if
      deallocate(a, ma)
      if (allocated(rc)) deallocate(rc)
   end subroutine prolong_band

   !> The mask follows the field through a tangential remap: mask <- mask(idx).
   subroutine remap_mask1(mask, map, out)
      logical, intent(in)  :: mask(:,:,:)
      type(prolong_axis_map), intent(in) :: map
      logical, intent(out) :: out(:,:,:)
      integer :: i, j, k
      do k = 1, size(mask, 3)
         do j = 1, size(mask, 2)
            do i = 1, map%nc
               out(i,j,k) = mask(map%idx(i),j,k)
            end do
         end do
      end do
   end subroutine remap_mask1

end module nesting_prolong
