#!/usr/bin/env python3
"""Cut the nested child case out of the parent's output.

Given a parent case directory that has finished its production phase, this
builds a complete, runnable child case:

* the same aligned cube array on the child's sub-domain -- generated by the
  same ``udgeom.create_cubes`` call, which reproduces the parent's array exactly
  because the child's origin is a whole number of cube periods;
* ``prof.inp`` seeded with the parent sub-region's own time- and
  plane-averaged ``<u>(z)``, ``<v>(z)`` so the child starts near equilibrium;
* ``namoptions.<nr>`` with ``lnesting = .true.`` and the zone geometry of the
  preset;
* ``nesting.inp.<nr>.nc``, written through the **production** writer
  ``tools/python/udprep/nesting.py`` (``slabs_from_fields`` into
  ``NestingWriter.append_level``, one parent level at a time), so the writer
  and the Fortran reader cannot drift apart -- and so that the slab cut holds
  one parent level rather than the whole record: its peak memory does not
  grow with the number of levels.

Because the refinement ratio is exactly 1 the slabs are *cut*, not interpolated
(``slabs_from_fields``): V1 is meant to isolate the nesting scheme from the
interpolation, which P1-P11 cover separately.

The child's clock starts at 0, so the parent dump times are shifted by
``t_offset = times[0]``.  ``manifest.json`` records the mapping.

Two driving sources (``--source``, :attr:`DrivingParent.source`): the parent's
full-domain ``fielddump`` files, or its ``nestparent`` band files (``&NESTPARENT``,
``src/nesting_parent.f90``, plan item D1) plus the ``nestparent_init`` block for the
initial condition.  Both go through the same cut, the same writer and produce
the same file; a parent run with both switches on at one cadence gives
bit-identical nesting files (``test_nestparent_tiny.py``).  The nestparent band has
no interior, so with that source the ``prof.inp`` seed and the recorded driving
parent profile come from the single initial block.

Usage
-----
    python make_child_case.py <parent_case_dir> <outdir> [--preset ...]
"""

from __future__ import annotations

import argparse
import json
from collections import OrderedDict
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

import numpy as np

import caselib
from caselib import (
    CoarsenedFieldDump,
    FieldDump,
    NestParent,
    check_finite_slabs,
    coarsen_fluid_mask,
    cube_geometry,
    load_solid_mask,
    run_preprocessing,
    write_lscale,
    write_namoptions,
    write_prof,
)
from config import Preset, RefinedPoint, get_preset

from udprep.nesting import (
    COMPONENTS,
    DEFAULT_PROLONGATION,
    NestGrid,
    NestingWriter,
    discrete_divergence,
    initial_fields_from_parent,
    slabs_from_fields,
    slabs_from_parent,
    stagger_masks_from_ibm,
)


def child_sections(preset: Preset, runtime: float) -> "OrderedDict":
    nr = preset.child_expnr
    return OrderedDict([
        ("RUN", OrderedDict([
            ("iexpnr", int(nr)),
            ("runmode", 1),
            ("runtime", runtime),
            ("dtmax", preset.dtmax),
            ("ladaptive", True),
            ("trestart", 1.0e9),
            ("lwarmstart", False),
            ("startfile", f"initd00000000_000_000.{nr}"),
            ("irandom", 43),
            ("randu", 0.1 * preset.u0),
            ("krand", preset.child_ktot),
            ("lrandomize", True),
            ("libm", True),
            ("lles", True),
            ("nprocx", preset.child_nprocx),
            ("nprocy", preset.child_nprocy),
        ])),
        ("DOMAIN", OrderedDict([
            ("itot", preset.child_itot),
            ("jtot", preset.child_jtot),
            ("ktot", preset.child_ktot),
            ("xlen", preset.child_xlen),
            ("ylen", preset.child_ylen),
        ])),
        ("PHYSICS", OrderedDict([
            ("ltempeq", False),
            ("lmoist", False),
            ("lbuoyancy", False),
            ("lcoriol", False),
            ("lprofforc", False),
            ("luvolflowr", False),
            ("lvvolflowr", False),
            ("igrw_damp", 0),
            # Identical to the parent's: the two runs must share the momentum
            # source exactly, or the comparison measures the forcing difference.
            ("dpdx", preset.dpdx),
        ])),
        ("DYNAMICS", OrderedDict([
            ("ipoiss", 0),  # POISS_FFT2D; lnesting requires it
        ])),
        ("BC", OrderedDict([
            ("BCxm", 4),   # BCxm_nesting
            ("BCym", 3),   # BCym_nesting
            ("BCbotm", 3),
            ("BCtopm", 1),
        ])),
        ("NAMSUBGRID", OrderedDict([
            ("lvreman", True),
        ])),
        ("WALLS", OrderedDict([
            ("iwallmom", 2),
            ("iwalltemp", 1),
            ("lwritefac", False),
        ])),
        ("NESTING", OrderedDict([
            ("lnesting", True),
            ("nestfile", f"nesting.inp.{nr}.nc"),
            ("nest_guardwidth", preset.guardwidth),
            ("nest_zonewidth", preset.zonewidth),
            ("nest_tau", preset.tau),
            ("nest_shape", 1),        # raised cosine
            # 1 = linear, 2 = Catmull-Rom cubic Hermite (unlimited, so flux
            # safe -- the monotone limiter that broke Phi = 0 in Finding N1 is
            # gone).  See config.Preset.timeinterp.
            ("nest_timeinterp", preset.timeinterp),
            ("nest_nwall", preset.nwall),
            # .false. asserts the design section 5 rule -- no solid points
            # anywhere W > 0 -- instead of merely warning about it.  The 'plaza'
            # geometry earns that by removing, from the *parent*, the cubes whose
            # footprint would fall in the child's guard + ramp band, so the zone
            # sits over open ground.  The 'uniform' geometry keeps the unbroken
            # array and needs .true.: legal only because the parent resolves the
            # same buildings (self-nesting), and the harder case.
            ("nest_lparentgeom", not preset.building_free_zone),
            ("nest_fluxtol", 1.0e-10),
            ("nest_lfluxassert", True),
            ("nest_linitfromparent", preset.init_from_parent),
            # .true. (the Fortran default) is every preset before V6: reading
            # past the last stored parent level is a configuration mistake and
            # should abort.  V6 sets this .false. on purpose -- design section
            # 10.4 row V6 wants exactly that "past the record" state, held
            # rather than fatal (nesting.check_record_end).
            ("nest_lendabort", preset.nest_lendabort),
            # -1.0 (the Fortran default: nest_statint <- tstatsdump) unless a
            # preset overrides it.  config.Preset.nest_statint's docstring
            # explains why V6 leaves this at the default here too and patches
            # it after the case is built instead.
            ("nest_statint", preset.nest_statint if preset.nest_statint is not None
                             else -1.0),
        ])),
        ("NAMCHECKSIM", OrderedDict([
            ("tcheck", max(1.0, runtime / 20.0)),
        ])),
        ("OUTPUT", OrderedDict([
            ("lfielddump", True),
            # The child's own dump interval, not the parent's: a 0.5 s parent
            # (C0b) drives children whose statistics are still taken at 3 s.
            ("tfielddump", preset.child_dtdump),
            ("fieldvars", "u0,v0,w0"),
        ])),
        ("INP", OrderedDict([
            ("zsize", preset.zsize),
            ("stl_file", f"geom.{nr}.stl"),
            ("u0", preset.u0),
            ("v0", 0.0),
            ("thl0", 288.0),
        ])),
    ])


def child_grid(preset: Preset) -> NestGrid:
    """The child's own grid, origin at 0 -- what ``nestio_validate`` compares."""
    return NestGrid.uniform(
        preset.child_itot, preset.child_jtot, preset.child_ktot,
        preset.child_xlen, preset.child_ylen, preset.zsize,
    )


@dataclass
class DrivingParent:
    """Where a child's boundary data comes from, and on what grid it arrives.

    The child's own description -- grid, geometry, zone, forcing -- always comes
    from the :class:`config.Preset`.  What this object adds is the *other* grid:
    the one the parent field lives on.  At refinement ratio 1 the two coincide
    and the slabs are **cut** (:func:`udprep.nesting.slabs_from_fields`); at
    ``refine > 1`` they do not and the slabs are **interpolated**
    (:func:`udprep.nesting.slabs_from_parent`), which is the only difference
    between V1 and V0 in this module.

    Keeping the two apart is what lets V0 point a child at data that did not
    come from the run it is compared against: the ``filtered`` arm drives the
    child from the fine reference's own dumps, box-filtered onto the coarse
    grid, while the ``coarse`` arm drives it from a genuinely coarse LES.  The
    child, the reference and every diagnostic are identical between them.
    """

    #: A :class:`caselib.FieldDump` or :class:`caselib.CoarsenedFieldDump`.
    dump: Any
    #: Experiment number of the *directory* the dumps were read from.
    source_expnr: str
    #: Spacing of the grid the data arrives on [m].
    dx: float
    #: ``dx / dx_child``.  1 reproduces V1 exactly.
    refine: int
    #: Factor the source directory's dumps are box-filtered by (1 unless the
    #: source is a finer run than the driving grid).
    coarsen: int
    #: Child window origin, in driving-grid columns.
    i0: int
    j0: int
    #: Driving grid extent, in its own cells.
    itot: int
    jtot: int
    ktot: int
    label: str
    #: ``"fielddump"`` -- full-domain dumps, every level holds the whole child
    #: window; ``"nestparent"`` -- the parent-side zone dump (``&NESTPARENT``,
    #: ``caselib.NestParent``), every level holds the band only and the initial
    #: block comes from the ``nestparent_init`` files.
    source: str = "fielddump"

    # -- constructors ------------------------------------------------------- #

    @classmethod
    def matched(cls, parent_dir: Path, preset: Preset,
                source: str = "fielddump") -> "DrivingParent":
        """V1: parent and child on one grid, slabs cut rather than interpolated."""
        dump = cls._open(parent_dir, preset.parent_expnr, preset.dx, source)
        return cls(
            dump=dump,
            source_expnr=preset.parent_expnr, dx=preset.dx, refine=1, coarsen=1,
            i0=preset.child_i0, j0=preset.child_j0,
            itot=preset.itot, jtot=preset.jtot, ktot=preset.ktot,
            label=f"{preset.parent_expnr} at {preset.dx:g} m (r = 1, slabs cut, {source})",
            source=source,
        )

    @classmethod
    def refined(cls, parent_dir: Path, point: RefinedPoint,
                source: str = "fielddump") -> "DrivingParent":
        """V0: the driving grid is ``point.refine`` times coarser than the child's."""
        d, c = point.driver, point.child
        if point.coarsen > 1:
            if source != "fielddump":
                raise ValueError(
                    "the filtered arm box-filters the fine reference's full dumps; "
                    "it cannot be driven from a nestparent band")
            dump: Any = CoarsenedFieldDump(
                FieldDump(parent_dir, point.reference_expnr, c.dx), point.coarsen)
            source_nr = point.reference_expnr
            label = (f"{source_nr} at {c.dx:g} m, box-filtered by {point.coarsen} "
                     f"onto the {d.dx:g} m grid (r = {point.refine}, slabs interpolated)")
        else:
            dump = cls._open(parent_dir, d.parent_expnr, d.dx, source)
            source_nr = d.parent_expnr
            label = (f"{source_nr} at {d.dx:g} m "
                     f"(r = {point.refine}, slabs interpolated, {source})")
        return cls(dump=dump, source_expnr=source_nr, dx=d.dx, refine=point.refine,
                   coarsen=point.coarsen, i0=d.child_i0, j0=d.child_j0,
                   itot=d.itot, jtot=d.jtot, ktot=d.ktot, label=label, source=source)

    @staticmethod
    def _open(parent_dir: Path, expnr: str, dx: float, source: str) -> Any:
        if source == "fielddump":
            return FieldDump(parent_dir, expnr, dx)
        if source == "nestparent":
            return NestParent(parent_dir, expnr, dx)
        raise ValueError(f"unknown driving source {source!r}; 'fielddump' or 'nestparent'")

    # -- derived ------------------------------------------------------------ #

    @property
    def interpolates(self) -> bool:
        return self.refine > 1

    @property
    def complete_levels(self) -> bool:
        """Whether every level holds the whole window (so a profile can be taken from it)."""
        return self.source == "fielddump"

    def window_cells(self, preset: Preset) -> Tuple[int, int, int]:
        """The child window, in driving-grid cells."""
        return (int(round(preset.child_xlen / self.dx)),
                int(round(preset.child_ylen / self.dx)),
                int(round(preset.zsize / self.dx)))

    def grid(self, preset: Preset) -> NestGrid:
        """The driving grid over the child window, in the child's own coordinates.

        ``conservative_interpolate`` needs parent and child coordinates in one
        frame, and the child's frame has its origin at 0 -- so the parent is
        described here as the window only, not the whole domain.  Nothing is
        lost: the writer never interpolates outside the zone slabs and the
        optional initial-condition block, both of which are inside the window.
        """
        ni, nj, nk = self.window_cells(preset)
        return NestGrid.uniform(ni, nj, nk, preset.child_xlen, preset.child_ylen,
                                preset.zsize)

    def fluid_window(self, parent_dir: Path, preset: Preset) -> np.ndarray:
        """The driving parent's fluid mask over the window, on the reduced grid.

        Shape ``(ni - 1, nj - 1, nk - 1)`` to match :func:`caselib.cell_centred`.
        Read from the source directory at *its* resolution and block-ANDed down
        when the source is finer than the driving grid, so a coarse cell counts
        as fluid only if all of it is.
        """
        ni, nj, nk = self.window_cells(preset)
        c = self.coarsen
        fluid = load_solid_mask(parent_dir,
                                (self.itot * c, self.jtot * c, self.ktot * c))
        fluid = coarsen_fluid_mask(fluid, c)
        return fluid[self.i0:self.i0 + ni - 1,
                     self.j0:self.j0 + nj - 1, :nk - 1]

    def fluid_mask(self, parent_dir: Path, preset: Preset) -> np.ndarray:
        """The driving parent's fluid mask over the *whole* window, cell-centred.

        Shape ``(ni, nj, nk)`` -- exactly :meth:`grid`'s cell count -- unlike
        :meth:`fluid_window`, which is one cell short on every axis to match
        :func:`caselib.cell_centred`'s reduction of the profile fields. This is
        the mask :func:`udprep.nesting.stagger_masks_from_ibm` needs to derive
        the staggered ``parent_masks`` that :func:`udprep.nesting.conservative_interpolate`
        (via ``slabs_from_parent`` / ``initial_fields_from_parent``) expects: a
        cell the interpolation stencil can reach must be covered, not just the
        interior columns the profile averages over.
        """
        ni, nj, nk = self.window_cells(preset)
        c = self.coarsen
        fluid = load_solid_mask(parent_dir,
                                (self.itot * c, self.jtot * c, self.ktot * c))
        fluid = coarsen_fluid_mask(fluid, c)
        return fluid[self.i0:self.i0 + ni, self.j0:self.j0 + nj, :nk]

    def interior_columns(self, preset: Preset) -> Tuple[np.ndarray, np.ndarray]:
        """Reduced-array columns outside the guard + ramp, on the driving grid.

        The same rule ``analyse.interior_indices`` applies to the child, so the
        driving parent's own profile is taken over the region the child's
        statistics are taken over -- to within the coarse grid's ability to
        resolve its edges, which is why it is recomputed here rather than
        rescaled from the child's.
        """
        lz = preset.guardwidth + preset.zonewidth
        ni, nj, _ = self.window_cells(preset)
        i = np.arange(ni - 1)
        j = np.arange(nj - 1)
        return (np.where(((i + 0.5) * self.dx >= lz)
                         & ((ni - i - 0.5) * self.dx >= lz))[0],
                np.where(((j + 0.5) * self.dx >= lz)
                         & ((nj - j - 0.5) * self.dx >= lz))[0])


def decompose_tke(imean: Dict[str, np.ndarray], imsq: Dict[str, np.ndarray],
                  cell_sum: Dict[str, np.ndarray], cell_sumsq: Dict[str, np.ndarray],
                  n_profile: float, icell: np.ndarray) -> Dict[str, np.ndarray]:
    """Split the driving parent's own resolved TKE into its temporal and
    dispersive parts, on the fluid-only interior profile.

    Both parts are real, physically meaningful quantities in a spatially
    heterogeneous flow (a canopy locks a spatial pattern into the time-mean
    field); this function reports both rather than picking one, and makes the
    ``tke`` this module emits consistent with the definition
    :class:`analyse.Bundle` uses everywhere else in the campaign (V1, V2, C0)
    and on the fine-truth side of this same V0 comparison.

    ``imean``/``imsq`` are ``accumulate_profile``'s running totals: the
    horizontal mean of ``q`` and of ``q**2``, summed level by level over the
    fluid interior.  Dividing by ``n_profile`` gives the combined space-and-time
    mean and mean-square, so::

        total = 0.5 * sum(imsq[c] / n_profile - (imean[c] / n_profile) ** 2
                          for c in "uvw")

    is the *old* estimator: resolved variance about the combined mean, which
    is exactly ``temporal + dispersive`` below (the cross term between a
    time-invariant spatial pattern and a spatially uniform temporal signal
    vanishes identically when both are expressed as deviations from their own
    means, so the identity is exact, not approximate).

    ``cell_sum``/``cell_sumsq`` are the same accumulation kept per CELL
    (shape ``(ni, nj, nkp)``, zero outside the fluid mask): dividing by
    ``n_profile`` gives each cell's own temporal mean and mean-square, so the
    fluid-only horizontal average of *that* cell's variance about *its own*
    mean is the temporal part -- pure turbulence, with the spatial variance of
    the time-mean field (the dispersive part) excluded because each cell is
    compared only against itself.

    Returns a dict with ``"temporal"``, ``"dispersive"`` and ``"total"``
    profiles, each an array of length ``nkp``.  ``dispersive`` is computed as
    ``total - temporal`` rather than from a separate spatial-variance formula:
    both quantities it is built from are independently correct, the identity
    above is exact, and computing it this way guarantees
    ``temporal + dispersive == total`` to floating-point round-off with no
    extra arithmetic to drift out of step.
    """
    total = 0.5 * sum(imsq[c] / n_profile - (imean[c] / n_profile) ** 2
                      for c in "uvw")
    temporal_component = {}
    for c in "uvw":
        qbar = cell_sum[c] / n_profile
        var_cell = cell_sumsq[c] / n_profile - qbar ** 2
        temporal_component[c] = var_cell.sum(axis=(0, 1)) / icell
    temporal = 0.5 * sum(temporal_component[c] for c in "uvw")
    dispersive = total - temporal
    return {"temporal": temporal, "dispersive": dispersive, "total": total}


def build(parent_dir: Path, outdir: Path, preset: Preset,
          ibm_backend: str = "auto", margin_levels: int = 2,
          driving: Optional[DrivingParent] = None) -> Path:
    """Build the child case in ``outdir`` from the parent dumps in ``parent_dir``.

    ``driving`` says which grid the parent data arrives on.  ``None`` -- the V1
    and V2 case -- means the parent's own grid at ``preset.dx``, and the slabs
    are cut.  A :class:`DrivingParent` at ``refine > 1`` means the data arrives
    coarser and the slabs are interpolated through the production prolongation;
    ``parent_dir`` is then the directory that object was built against, which
    for V0's filtered arm is the *fine* reference run, not a coarse one.
    """
    nr = preset.child_expnr
    casedir = Path(outdir) / nr
    casedir.mkdir(parents=True, exist_ok=True)
    zf = (np.arange(preset.child_ktot) + 0.5) * preset.dz
    # config.Preset.prolongation is None on every preset before V0b (and on
    # V0b's own reference/driver objects, which are never interpolated
    # against): resolving it here to the writer's own default keeps this
    # explicit in the manifest without changing what gets passed to
    # slabs_from_parent/initial_fields_from_parent when it is unset -- the
    # writer's default IS udprep.nesting.DEFAULT_PROLONGATION, so passing it
    # explicitly is a no-op (plan section 7, R2; review finding 2).
    prolongation = preset.prolongation or DEFAULT_PROLONGATION

    # ---- geometry and a placeholder profile, then preprocessing ---------- #
    # The child's own layout, which is the parent's restriction minus whatever
    # would have landed in the guard + ramp band (config.Preset.child_cube_centres,
    # design section 9.4).  For V1 that subtraction is empty and the child is an
    # exact sub-model of the parent; for the V2 size arm it is not, and the
    # difference is confined to the band -- Preset.validate refuses a preset
    # where a cleared cube would also reach the analysis interior.
    cube_geometry(preset, preset.child_origin[0], preset.child_origin[1],
                  preset.child_xlen, preset.child_ylen, casedir / f"geom.{nr}.stl",
                  centres=preset.child_cube_centres())
    write_prof(casedir / f"prof.inp.{nr}", zf, u=preset.u0, v=0.0, e12=preset.tke0,
               comment="placeholder; overwritten with the parent's own profile below")
    # pgx = 0 on purpose; the forcing lives in &PHYSICS dpdx.  See the
    # docstring of caselib.write_lscale before changing this.
    write_lscale(casedir / f"lscale.inp.{nr}", zf,
                 comment="V1 big-brother child: forcing is dpdx in &PHYSICS")

    if driving is None:
        driving = DrivingParent.matched(parent_dir, preset)
    dump = driving.dump
    all_times = np.asarray(dump.times, dtype=float)
    # -- the boundary cadence: which of the parent's levels the child gets -- #
    # Every ``stride``-th dumped level, chosen BEFORE anything is read: the
    # loop below reads levels by index, so the levels that are skipped are
    # never touched and the I/O of the slab cut shrinks with the cadence,
    # not just the array.  ``times``, ``n_use``, ``runtime``, ``t_offset``
    # and ``parent_dt`` are all taken from the subsampled axis.
    stride = preset.cadence_stride
    levels = np.arange(0, all_times.size, stride)
    times = all_times[levels]
    if times.size < 4:
        raise RuntimeError(
            f"the parent wrote {all_times.size} field dumps, {times.size} at a "
            f"{preset.cadence:g} s cadence (every {stride}); V1 needs a time series"
        )
    # Stop the child short of the last stored level so the target is always
    # interpolated, never held constant past the end of the record.
    n_use = times.size
    runtime = float(times[-1 - margin_levels] - times[0])
    parent_dt = float(np.median(np.diff(times)))
    print(f"[make_child_case] cadence {preset.cadence:g} s: every {stride} of "
          f"{all_times.size} parent levels -> {n_use} levels, dt_P = {parent_dt:.3f} s, "
          f"C_dump = {preset.c_dump_u0:.2f} at u0 = {preset.u0:g} m/s")

    write_namoptions(
        casedir / f"namoptions.{nr}",
        child_sections(preset, runtime),
        header=[
            f"V1 Big Brother child, preset '{preset.name}'",
            "generated by tests/validation/nesting/make_child_case.py; do not hand-edit",
            f"driven by {parent_dir}",
        ],
    )
    run_preprocessing(casedir, ibm_backend=ibm_backend)

    # ---- cut or interpolate the slabs, accumulating the profile on the way - #
    grid = child_grid(preset)
    pgrid = driving.grid(preset)
    pi0, pj0 = driving.i0, driving.j0
    pni, pnj, pnk = driving.window_cells(preset)
    nzone = preset.nzone
    # The profile that seeds prof.inp is accumulated on the grid the parent data
    # ARRIVES on, which is the child's own only at refinement ratio 1.  At r > 1
    # it is the coarse grid and the profile is interpolated onto the child's
    # levels at the end; interpolating every parent level onto the whole child
    # instead would cost about as much as the slab cut and buy nothing, since
    # prof.inp carries a horizontal mean.
    if driving.interpolates:
        fluid = driving.fluid_window(parent_dir, preset)
        # W8's solid-aware slope logic (udprep.nesting._tangential_slopes) only
        # engages when conservative_interpolate is given parent_mask: derive
        # the three staggered masks from the parent's own IBM fluid mask over
        # the window, so a coarse stencil that touches a parent solid does not
        # leak the solid's near-zero velocity into a neighbouring fluid slope
        # (review finding R3 / plan item W7's FaceMasks note).
        parent_masks = stagger_masks_from_ibm(driving.fluid_mask(parent_dir, preset))
    else:
        # Fluid in the child AND in the parent.  The profile below is accumulated
        # from the *parent's* field, so a cell the child cleared out of its zone --
        # fluid in the child, solid in the parent -- would contribute the parent's
        # near-zero in-building velocity to it.  Same intersection, and same reason,
        # as analyse.run.  A no-op wherever the two geometries agree, i.e. always
        # unless clear_child_zone is set.
        shape = (preset.child_itot - 1, preset.child_jtot - 1, preset.child_ktot - 1)
        fluid = load_solid_mask(casedir, shape)
        if preset.clear_child_zone:
            pfluid = load_solid_mask(parent_dir, (preset.itot, preset.jtot, preset.ktot))
            fluid = fluid & pfluid[preset.child_i0:preset.child_i0 + shape[0],
                                   preset.child_j0:preset.child_j0 + shape[1], :shape[2]]
    nkp = fluid.shape[2]
    usum = np.zeros(nkp)
    vsum = np.zeros(nkp)
    ncell = fluid.sum(axis=(0, 1)).astype(float)
    ncell[ncell == 0] = np.nan
    # The driving parent's own interior statistics, on its own grid.  Free here
    # -- the loop already holds every level -- and the only way to tell a child
    # that failed to reproduce the truth from a child that faithfully reproduced
    # a parent which was itself wrong.  Reported by analyse_v0, never used to
    # drive anything.
    ii_p, jj_p = driving.interior_columns(preset)
    isel = fluid[np.ix_(ii_p, jj_p)]
    icell = isel.sum(axis=(0, 1)).astype(float)
    icell[icell == 0] = np.nan
    imean = {c: np.zeros(nkp) for c in "uvw"}
    imsq = {c: np.zeros(nkp) for c in "uvw"}
    # Per-CELL temporal sums of q and q^2 over the same interior columns and
    # fluid mask as imean/imsq above, but not yet reduced horizontally: this is
    # what lets the profile below distinguish temporal turbulence (each cell's
    # own variance about its own time mean, analyse.Bundle's definition) from
    # the dispersive variance of the time-mean field across cells, which imean
    # and imsq alone cannot separate.  Shape (len(ii_p), len(jj_p), nkp) per
    # component -- a few tens of MB at the production interior size (~104^2 x
    # 64), see decompose_tke's docstring -- so, unlike the full parent record,
    # affordable to hold for the run of the loop.
    cell_sum = {c: np.zeros((ii_p.size, jj_p.size, nkp)) for c in "uvw"}
    cell_sumsq = {c: np.zeros((ii_p.size, jj_p.size, nkp)) for c in "uvw"}
    # How many levels the profiles below are averaged over.  A full-domain dump
    # contributes every level; a nestparent band has no interior, so the profile
    # (which only seeds prof.inp and reports what the parent knew) is taken
    # from the single initial block instead.
    n_profile = n_use if driving.complete_levels else 1

    # ---- a SECOND interior accumulation, restricted to the analysis window - #
    # ``imean``/``imsq``/``cell_sum``/``cell_sumsq`` above (and hence prof.inp,
    # via usum/vsum) deliberately span every supplied level -- prof.inp only
    # has to start the child near equilibrium, and using everything the loop
    # already holds costs nothing extra.  But ``analyse.run`` restricts the
    # reference/child comparison to ``stats_start <= t <= runtime``
    # (analyse.py's ``t0``/``t1``, read from this same manifest), so an
    # interior profile handed to ``analyse_v0.parent_deficit`` for validation
    # against that comparison must be accumulated over the SAME window, not
    # over the child's adjustment period and end margins too (review finding
    # 4: for V0b the full-record profile spans ~0-2400 s over 4800 levels
    # while the reference spans 600-2398.41 s over 600 samples). These
    # ``*_valid`` accumulators are that window-restricted profile; ``imean``
    # etc. above are untouched and still seed prof.inp exactly as before.
    validation_t0 = float(preset.child_spinup)
    validation_t1 = runtime
    imean_valid = {c: np.zeros(nkp) for c in "uvw"}
    imsq_valid = {c: np.zeros(nkp) for c in "uvw"}
    cell_sum_valid = {c: np.zeros((ii_p.size, jj_p.size, nkp)) for c in "uvw"}
    cell_sumsq_valid = {c: np.zeros((ii_p.size, jj_p.size, nkp)) for c in "uvw"}
    validation_times: List[float] = []

    def accumulate_profile(cu, cv, cw, t_local: float) -> None:
        uc, vc, wc = caselib.cell_centred(cu[:-1], cv[:, :-1], cw[:, :, :-1])
        usum[:] += np.where(fluid, uc, 0.0).sum(axis=(0, 1)) / ncell
        vsum[:] += np.where(fluid, vc, 0.0).sum(axis=(0, 1)) / ncell
        in_window = validation_t0 - 1.0e-6 <= t_local <= validation_t1 + 1.0e-6
        if in_window:
            validation_times.append(t_local)
        for c, arr in zip("uvw", (uc, vc, wc)):
            blk = arr[np.ix_(ii_p, jj_p)]
            masked = np.where(isel, blk, 0.0)
            sq = np.where(isel, blk * blk, 0.0)
            imean[c] += masked.sum(axis=(0, 1)) / icell
            imsq[c] += sq.sum(axis=(0, 1)) / icell
            cell_sum[c] += masked
            cell_sumsq[c] += sq
            if in_window:
                imean_valid[c] += masked.sum(axis=(0, 1)) / icell
                imsq_valid[c] += sq.sum(axis=(0, 1)) / icell
                cell_sum_valid[c] += masked
                cell_sumsq_valid[c] += sq

    # ---- the nesting file, through the production per-level writer ------- #
    # The temporal ratio parent_dt / dtmax -- the boundary cadence over the
    # child's CFL step -- exceeds the design's V5 bound of 30 for every
    # production preset.  That bound predates the cadence study (C0), whose
    # criterion is C_dump; the writer evaluates and logs it.  The violation
    # is allowed explicitly, with this reason, and the verdict is recorded in
    # the manifest below rather than silenced.
    refinement_reason = (
        "temporal ratio parent_dt/dtmax is the parent dump cadence over the child's "
        "CFL-limited step; the boundary cadence is bounded by C_dump instead"
    )
    # Each level is appended as soon as it is cut: the writer corrects its
    # divergence on arrival, stores the pre- and post-correction residuals, and
    # syncs and projects the initial condition against the corrected level 0.
    # Nothing but the current parent level is held, so the slab cut's memory
    # is set by the parent's level size, not by the record length -- the
    # production record (thousands of levels) does not fit any other way.
    # The correction is summed over all four lateral faces, as it was when
    # apply_divergence_correction ran here on the whole record; a preset whose
    # lateral faces cut buildings is where udprep.nesting.face_masks_from_ibm
    # would be passed as ``masks``, and where the file's fluid_lateral_area
    # would start to match the solver's.
    nestfile = casedir / f"nesting.inp.{nr}.nc"
    writer = NestingWriter(
        nestfile, grid, nzone,
        parent_model=f"udales:{driving.source_expnr}:{preset.name}",
        parent_dx=driving.dx,
        parent_dt=parent_dt,
        child_origin_x=preset.child_origin[0],
        child_origin_y=preset.child_origin[1],
        child_dt=preset.dtmax,
        allow_refinement_violation=True,
        refinement_reason=refinement_reason,
    )
    # Post-correction residual of every stored level, from the writer's own
    # recomputation of what it wrote -- the number the solver validates against.
    phi_after = np.empty(n_use, dtype=np.float64)
    has_initial = False
    div0 = None
    div_parent0 = None
    with writer:
        for n, lev in enumerate(levels):
            pu, pv, pw = dump.read_level(int(lev))
            cu, cv, cw = dump.child_block(pu, pv, pw, pi0, pj0, pni, pnj)
            initial_fields = None
            if n == 0 and not driving.complete_levels:
                # The band has no interior: the initial block is the parent's
                # separate whole-box write at the first dump time, which is
                # the instant of level 0 (nesting_parent writes both from the
                # same field).  It also stands in for the profile.
                iu, iv, iw = dump.read_init()
                if abs(float(dump.init_time) - float(all_times[0])) > 1.0e-6:
                    raise RuntimeError(
                        f"nestparent_init is stamped t = {dump.init_time} but the first "
                        f"band level is t = {all_times[0]}")
                accumulate_profile(iu, iv, iw, float(dump.init_time) - float(times[0]))
                if preset.init_from_parent:
                    cu, cv, cw = iu, iv, iw
            if n == 0 and preset.init_from_parent:
                # Schema 2's optional full-domain block: the child cold-starts from
                # the parent's own instantaneous field, so the interior turbulence
                # is the parent's from the first step instead of having to grow in
                # from the boundaries.  The writer syncs it to the corrected
                # boundary data of level 0 and projects it before storing it.
                if driving.interpolates:
                    initial_fields = initial_fields_from_parent(
                        pgrid, cu, cv, cw, grid, parent_masks=parent_masks,
                        prolongation=prolongation,
                    )
                    div0 = float(np.max(np.abs(discrete_divergence(
                        grid, initial_fields["u"], initial_fields["v"],
                        initial_fields["w"]))))
                    # Design section 1.3: the prolongation reproduces the parent's
                    # discrete divergence cell by cell, so a solenoidal parent gives
                    # a solenoidal child target.  Recording the parent's own divmax
                    # next to the child's turns that from an assertion in a docstring
                    # into a number in the manifest -- and it is the offline half of
                    # the end-to-end check the runtime `divmax` completes.
                    div_parent0 = float(np.max(np.abs(
                        discrete_divergence(pgrid, cu, cv, cw))))
                else:
                    # copies: the profile below still needs the parent's own field
                    initial_fields = {"u": cu.copy(), "v": cv.copy(), "w": cw.copy()}
                    div0 = float(np.max(np.abs(discrete_divergence(grid, cu, cv, cw))))
                has_initial = True
            if driving.interpolates:
                level = slabs_from_parent(pgrid, cu, cv, cw, child=grid, nzone=nzone,
                                          parent_masks=parent_masks,
                                          prolongation=prolongation)
            else:
                level = slabs_from_fields(grid, nzone, cu, cv, cw)
            # A slab that reached past a nestparent band is NaN, not zero.
            check_finite_slabs(level, getattr(dump, "nzone", pni), driving.dx)
            phi_after[n] = writer.append_level(
                times[n] - times[0], level, initial_fields=initial_fields,
            )["flux_residual"]
            if driving.complete_levels:
                accumulate_profile(cu, cv, cw, float(times[n] - times[0]))
    # cadence, correction and refinement, accumulated level by level in the
    # writer; the refinement verdict already carries "allowed" and the reason
    diagnostics = writer.diagnostics
    # Largest pre-correction |Phi| over the record, as the writer saw it arrive
    phi_before_max = float(diagnostics["correction"]["residual_max_abs"])
    phi_after_max = float(np.max(np.abs(phi_after)))
    # Total lateral boundary area -- the normalisation nesting's
    # check_stored_flux uses (phi = sum(rho u_n dA) / area_bnd).
    area = 2.0 * (grid.xlen + grid.ylen) * grid.zsize
    # The stored initial condition is the synced and projected one; its
    # divergence is measured on what the solver will read, not on a copy.
    ic_after = _initial_condition_divmax(nestfile, grid) if has_initial else None

    pzf = (np.arange(nkp) + 0.5) * driving.dx
    if driving.interpolates:
        # The coarse profile carried onto the child's levels.  prof.inp only has
        # to start the child near equilibrium -- with nest_linitfromparent the
        # velocity field is overwritten by the interpolated parent block anyway
        # -- so linear interpolation, held constant outside the coarse range, is
        # ample and is not a claim about sub-parent-scale structure.
        uprof = np.interp(zf, pzf, usum / n_profile)
        vprof = np.interp(zf, pzf, vsum / n_profile)
        prof_comment = (f"driving parent ({driving.label}) time- and plane-mean "
                        f"profile, fluid cells only, interpolated from its "
                        f"{driving.dx:g} m levels")
    else:
        uprof = np.empty(preset.child_ktot)
        vprof = np.empty(preset.child_ktot)
        uprof[:-1] = usum / n_profile
        vprof[:-1] = vsum / n_profile
        uprof[-1] = uprof[-2]
        vprof[-1] = vprof[-2]
        prof_comment = ("parent sub-region time- and plane-mean profile "
                        "(fluid cells only)"
                        + ("" if driving.complete_levels else
                           ", from the nestparent initial block only"))
    write_prof(casedir / f"prof.inp.{nr}", zf, u=uprof, v=vprof, e12=preset.tke0,
               comment=prof_comment)
    # ---- the VALIDATION profile: windowed, not the full record ----------- #
    # imean/imsq/cell_sum/cell_sumsq above span every supplied level and only
    # feed prof.inp (unchanged above). analyse_v0.parent_deficit instead
    # compares this profile against analyse.run's parent/child statistics,
    # which are restricted to stats_start <= t <= runtime -- so the profile
    # handed to it here has to be the *_valid accumulation over that same
    # window (review finding 4), not n_profile's full-record one.
    n_profile_valid = len(validation_times)
    window_note = (f"analysis window [{validation_t0:g}, {validation_t1:g}] s "
                   "(manifest stats_start .. runtime)")
    if n_profile_valid >= 2:
        tke_parts = decompose_tke(imean_valid, imsq_valid, cell_sum_valid,
                                  cell_sumsq_valid, n_profile_valid, icell)
        tke_unavailable_reason = None
    elif n_profile_valid == 1:
        # One sample gives a well-defined mean but a zero, meaningless variance.
        tke_parts = {"temporal": None, "dispersive": None, "total": None}
        tke_unavailable_reason = (
            f"only one driving-parent level falls inside the {window_note}: "
            "no time series to take a temporal statistic over")
    else:
        # Either a nestparent (band-only) source, whose single initial block sits
        # at t = 0 and essentially never falls inside stats_start..runtime, or
        # a complete-levels source whose record does not reach the window at
        # all. Either way: no interior field over the window, so none of
        # temporal/dispersive/total -- or even a mean -- is available. Emit the
        # marker instead of a number analyse_v0.parent_deficit would otherwise
        # silently accept.
        tke_parts = {"temporal": None, "dispersive": None, "total": None}
        tke_unavailable_reason = (
            f"no driving-parent levels fall inside the {window_note}"
            + ("" if driving.complete_levels else
               " (nestparent band source: only the single t=0 initial block "
               "is available, and it does not fall inside stats_start)"))
    mean_available = n_profile_valid > 0
    driving_profile = {
        "grid": "driving parent, its own cell centres",
        "source": driving.label,
        "dx_m": driving.dx,
        "z": pzf.tolist(),
        "interior_columns": [int(ii_p.size), int(jj_p.size)],
        # The window this profile (u/v/w/tke below) was accumulated over --
        # analyse_v0.parent_deficit asserts this matches the manifest's own
        # "stats_start"/"runtime" before comparing anything, refusing the
        # comparison rather than silently mixing windows if it does not.
        "window_s": [validation_t0, validation_t1],
        "n_levels_in_window": int(n_profile_valid),
        "mean_available": mean_available,
        "u": (imean_valid["u"] / n_profile_valid).tolist() if mean_available else None,
        "v": (imean_valid["v"] / n_profile_valid).tolist() if mean_available else None,
        "w": (imean_valid["w"] / n_profile_valid).tolist() if mean_available else None,
        # "tke": pure temporal turbulence -- each fluid cell's own variance
        # about its own time mean, then averaged horizontally.  This is the
        # definition analyse.Bundle.tke uses everywhere else in the campaign
        # (V1, V2, C0) and on the fine-truth side of this same comparison, so
        # it is what this module now reports too: a consistency choice, not a
        # claim that the alternative below is wrong.
        # "tke_dispersive": the spatial variance, over the same fluid interior,
        # of the local time-mean field -- the dispersive kinetic energy a fixed
        # canopy geometry locks into the mean flow.  Real and physically
        # meaningful, not an error; reported rather than discarded.
        # "tke_total": their sum, exactly what the combined space-and-time-mean
        # formula this module used to report gives -- unchanged, still here,
        # just no longer the thing compared against a purely temporal truth.
        "tke": (tke_parts["temporal"].tolist() if tke_parts["temporal"] is not None
                else None),
        "tke_dispersive": (tke_parts["dispersive"].tolist()
                           if tke_parts["dispersive"] is not None else None),
        "tke_total": (tke_parts["total"].tolist() if tke_parts["total"] is not None
                     else None),
        "tke_unavailable_reason": tke_unavailable_reason,
        "n_levels": int(n_profile),
        "note": ("interior-only, fluid-only, over the same guard + ramp exclusion "
                 "the child's statistics use, on the driving grid; this is what "
                 "the parent itself knew, restricted to the analysis window "
                 "recorded in 'window_s' (NOT 'n_levels', which counts every "
                 "supplied level and only describes what seeded prof.inp). "
                 "'tke' is the per-cell temporal variance (analyse.Bundle's "
                 "definition); 'tke_dispersive' is the spatial variance of the "
                 "time-mean field; 'tke_total' is their sum"
                 + ("" if mean_available else
                    "; no level fell inside the analysis window, so even the "
                    "mean profile is unavailable -- see tke_unavailable_reason")),
    }

    # ---- the manifest ----------------------------------------------------- #
    manifest = {
        "preset": preset.name,
        "parent_dir": str(Path(parent_dir).resolve()),
        "driving_source": driving.source,
        "refinement": {
            "spatial": driving.refine,
            "spatial_from_file": diagnostics["refinement"]["spatial"],
            "temporal_from_file": diagnostics["refinement"]["temporal"],
            "parent_dx_m": driving.dx,
            "child_dx_m": preset.dx,
            "parent_nyquist_wavelength_m": 2.0 * driving.dx,
            "source": driving.label,
            "source_expnr": driving.source_expnr,
            "coarsen_factor": driving.coarsen,
            "slabs": ("interpolated (slabs_from_parent)" if driving.interpolates
                      else "cut (slabs_from_fields)"),
            "parent_window_cells": [pni, pnj, pnk],
            "check": diagnostics["refinement"],
        },
        # NestingWriter.diagnostics as it is: ntime, cadence, correction and
        # the refinement verdict (the same object as refinement.check above)
        "writer_diagnostics": diagnostics,
        "driving_parent_profile": driving_profile,
        "child_expnr": nr,
        "parent_expnr": preset.parent_expnr,
        "t_offset": float(times[0]),
        "runtime": runtime,
        "n_parent_levels": int(n_use),
        "parent_dt_median": parent_dt,
        "cadence": {
            "seconds": float(preset.cadence),
            "stride": int(stride),
            "parent_dt": parent_dt,
            "dump_dt": float(preset.dtdump),
            "n_levels_dumped": int(all_times.size),
            "n_levels_used": int(n_use),
            "child_dtdump": float(preset.child_dtdump),
            "C_dump_at_u0": float(preset.c_dump_u0),
            "u0": float(preset.u0),
            "note": ("every 'stride'-th parent dump level is read and stored; the "
                     "others are never opened.  C_dump = u0 * cadence / dx is a "
                     "label at the initial bulk wind, not the criterion, which is "
                     "evaluated at the largest wind in the zone"),
        },
        "stats_start": float(preset.child_spinup),
        "child_i0": preset.child_i0,
        "child_j0": preset.child_j0,
        "ustar": preset.ustar,
        "dpdx": preset.dpdx,
        "flux_residual_before_correction": {
            "max_abs": phi_before_max,
            "max_abs_normalised": phi_before_max / area,
        },
        "flux_residual_after_correction": {
            "max_abs": phi_after_max,
            "max_abs_normalised": phi_after_max / area,
        },
        "nest_timeinterp": preset.timeinterp,
        # Only exercised when driving.interpolates (refine > 1); recorded
        # regardless so a matched-grid manifest states plainly that the field
        # was never consulted.  "preset.prolongation" is the config-level
        # request (None means "let the writer pick"); "prolongation" is what
        # was actually resolved and passed to slabs_from_parent /
        # initial_fields_from_parent above.
        "prolongation_requested": preset.prolongation,
        "prolongation": prolongation if driving.interpolates else None,
        "init_from_parent": bool(preset.init_from_parent),
        "geometry": preset.geometry,
        "building_free_zone": bool(preset.building_free_zone),
        "n_cubes_parent": int(len(preset.cube_centres())),
        "n_cubes_child": int(len(preset.child_cube_centres())),
        "n_cubes_child_in_parent_window": int(len(preset.cube_centres_in(
            preset.child_origin[0], preset.child_origin[1],
            preset.child_xlen, preset.child_ylen))),
        "clear_child_zone": bool(preset.clear_child_zone),
        "n_cubes_cleared_from_child_zone": int(preset.n_child_cubes_removed),
        "initial_condition_divmax": {
            "parent_before_prolongation": div_parent0,
            "before_projection": div0,
            "after_projection": ic_after,
        },
    }
    (casedir / "manifest.json").write_text(json.dumps(manifest, indent=2) + "\n",
                                           encoding="ascii")
    return casedir


def _initial_condition_divmax(nestfile: Path, grid: NestGrid) -> float:
    """Peak discrete divergence of the ``u_init``/``v_init``/``w_init`` block stored in ``nestfile``.

    Read back directly rather than through ``read_nesting_file``, which would
    load every slab level -- the record the streaming cut just avoided holding.
    """
    from netCDF4 import Dataset

    with Dataset(nestfile, "r") as ds:
        fields = [np.asarray(ds.variables[f"{c}_init"][:], dtype=np.float64)
                  for c in COMPONENTS]
    return float(np.max(np.abs(discrete_divergence(grid, *fields))))


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("parent_dir", type=Path)
    parser.add_argument("outdir", type=Path)
    parser.add_argument("--preset", default="production")
    parser.add_argument("--ibm-backend", default="auto")
    parser.add_argument("--source", default="fielddump", choices=("fielddump", "nestparent"),
                        help="which parent output to build from: the full field dumps "
                             "or the &NESTPARENT band files")
    args = parser.parse_args()

    preset = get_preset(args.preset)
    driving = DrivingParent.matched(args.parent_dir, preset, source=args.source)
    try:
        casedir = build(args.parent_dir, args.outdir, preset,
                        ibm_backend=args.ibm_backend, driving=driving)
    finally:
        driving.dump.close()
    manifest = json.loads((casedir / "manifest.json").read_text())
    print(f"child case written to {casedir}")
    cad = manifest["cadence"]
    print(f"  {manifest['n_parent_levels']} parent levels (every {cad['stride']} of "
          f"{cad['n_levels_dumped']} dumped; cadence {cad['seconds']:g} s), dt_P = "
          f"{manifest['parent_dt_median']:.3f} s, child runtime {manifest['runtime']:.1f} s")
    print(f"  Phi before correction  max |Phi|/A = "
          f"{manifest['flux_residual_before_correction']['max_abs_normalised']:.3e} m/s")
    print(f"  Phi after correction   max |Phi|/A = "
          f"{manifest['flux_residual_after_correction']['max_abs_normalised']:.3e} m/s")
    ic = manifest["initial_condition_divmax"]
    if ic["before_projection"] is not None:
        print(f"  initial condition divmax {ic['before_projection']:.3e} -> "
              f"{ic['after_projection']:.3e} after projection")


if __name__ == "__main__":
    main()
