#!/usr/bin/env python3
"""Cut the nested child case out of the parent's output.

Given a parent case directory that has finished its production phase, this
builds a complete, runnable child case:

* the same aligned cube array on the child's sub-domain -- generated by the
  same ``udgeom.create_cubes`` call, which reproduces the parent's array exactly
  because the child's origin is a whole number of cube periods;
* ``prof.inp`` seeded with the parent sub-region's own time- and
  plane-averaged ``<u>(z)``, ``<v>(z)`` so the child starts near equilibrium;
* ``namoptions.<nr>`` with ``lnesting = .true.`` and the zone geometry of the
  preset;
* ``nesting.inp.<nr>.nc``, written through the **production** writer
  ``tools/python/udprep/nesting.py`` (``slabs_from_fields`` into
  ``NestingWriter.append_level``, one parent level at a time), so the writer
  and the Fortran reader cannot drift apart -- and so that the slab cut holds
  one parent level rather than the whole record: its peak memory does not
  grow with the number of levels.

Because the refinement ratio is exactly 1 the slabs are *cut*, not interpolated
(``slabs_from_fields``): V1 is meant to isolate the nesting scheme from the
interpolation, which P1-P11 cover separately.

The child's clock starts at 0, so the parent dump times are shifted by
``t_offset = times[0]``.  ``manifest.json`` records the mapping.

Usage
-----
    python make_child_case.py <parent_case_dir> <outdir> [--preset ...]
"""

from __future__ import annotations

import argparse
import json
from collections import OrderedDict
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Optional, Tuple

import numpy as np

import caselib
from caselib import (
    CoarsenedFieldDump,
    FieldDump,
    coarsen_fluid_mask,
    cube_geometry,
    load_solid_mask,
    run_preprocessing,
    write_lscale,
    write_namoptions,
    write_prof,
)
from config import Preset, RefinedPoint, get_preset

from udprep.nesting import (
    COMPONENTS,
    NestGrid,
    NestingWriter,
    discrete_divergence,
    initial_fields_from_parent,
    slabs_from_fields,
    slabs_from_parent,
)


def child_sections(preset: Preset, runtime: float) -> "OrderedDict":
    nr = preset.child_expnr
    return OrderedDict([
        ("RUN", OrderedDict([
            ("iexpnr", int(nr)),
            ("runmode", 1),
            ("runtime", runtime),
            ("dtmax", preset.dtmax),
            ("ladaptive", True),
            ("trestart", 1.0e9),
            ("lwarmstart", False),
            ("startfile", f"initd00000000_000_000.{nr}"),
            ("irandom", 43),
            ("randu", 0.1 * preset.u0),
            ("krand", preset.child_ktot),
            ("lrandomize", True),
            ("libm", True),
            ("lles", True),
            ("nprocx", preset.child_nprocx),
            ("nprocy", preset.child_nprocy),
        ])),
        ("DOMAIN", OrderedDict([
            ("itot", preset.child_itot),
            ("jtot", preset.child_jtot),
            ("ktot", preset.child_ktot),
            ("xlen", preset.child_xlen),
            ("ylen", preset.child_ylen),
        ])),
        ("PHYSICS", OrderedDict([
            ("ltempeq", False),
            ("lmoist", False),
            ("lbuoyancy", False),
            ("lcoriol", False),
            ("lprofforc", False),
            ("luvolflowr", False),
            ("lvvolflowr", False),
            ("igrw_damp", 0),
            # Identical to the parent's: the two runs must share the momentum
            # source exactly, or the comparison measures the forcing difference.
            ("dpdx", preset.dpdx),
        ])),
        ("DYNAMICS", OrderedDict([
            ("ipoiss", 0),  # POISS_FFT2D; lnesting requires it
        ])),
        ("BC", OrderedDict([
            ("BCxm", 4),   # BCxm_nesting
            ("BCym", 3),   # BCym_nesting
            ("BCbotm", 3),
            ("BCtopm", 1),
        ])),
        ("NAMSUBGRID", OrderedDict([
            ("lvreman", True),
        ])),
        ("WALLS", OrderedDict([
            ("iwallmom", 2),
            ("iwalltemp", 1),
            ("lwritefac", False),
        ])),
        ("NESTING", OrderedDict([
            ("lnesting", True),
            ("nestfile", f"nesting.inp.{nr}.nc"),
            ("nest_guardwidth", preset.guardwidth),
            ("nest_zonewidth", preset.zonewidth),
            ("nest_tau", preset.tau),
            ("nest_shape", 1),        # raised cosine
            # 1 = linear, 2 = Catmull-Rom cubic Hermite (unlimited, so flux
            # safe -- the monotone limiter that broke Phi = 0 in Finding N1 is
            # gone).  See config.Preset.timeinterp.
            ("nest_timeinterp", preset.timeinterp),
            ("nest_nwall", preset.nwall),
            # .false. asserts the design section 5 rule -- no solid points
            # anywhere W > 0 -- instead of merely warning about it.  The 'plaza'
            # geometry earns that by removing, from the *parent*, the cubes whose
            # footprint would fall in the child's guard + ramp band, so the zone
            # sits over open ground.  The 'uniform' geometry keeps the unbroken
            # array and needs .true.: legal only because the parent resolves the
            # same buildings (self-nesting), and the harder case.
            ("nest_lparentgeom", not preset.building_free_zone),
            ("nest_fluxtol", 1.0e-10),
            ("nest_lfluxassert", True),
            ("nest_linitfromparent", preset.init_from_parent),
        ])),
        ("NAMCHECKSIM", OrderedDict([
            ("tcheck", max(1.0, runtime / 20.0)),
        ])),
        ("OUTPUT", OrderedDict([
            ("lfielddump", True),
            # The child's own dump interval, not the parent's: a 0.5 s parent
            # (C0b) drives children whose statistics are still taken at 3 s.
            ("tfielddump", preset.child_dtdump),
            ("fieldvars", "u0,v0,w0"),
        ])),
        ("INP", OrderedDict([
            ("zsize", preset.zsize),
            ("stl_file", f"geom.{nr}.stl"),
            ("u0", preset.u0),
            ("v0", 0.0),
            ("thl0", 288.0),
        ])),
    ])


def child_grid(preset: Preset) -> NestGrid:
    """The child's own grid, origin at 0 -- what ``nestio_validate`` compares."""
    return NestGrid.uniform(
        preset.child_itot, preset.child_jtot, preset.child_ktot,
        preset.child_xlen, preset.child_ylen, preset.zsize,
    )


@dataclass
class DrivingParent:
    """Where a child's boundary data comes from, and on what grid it arrives.

    The child's own description -- grid, geometry, zone, forcing -- always comes
    from the :class:`config.Preset`.  What this object adds is the *other* grid:
    the one the parent field lives on.  At refinement ratio 1 the two coincide
    and the slabs are **cut** (:func:`udprep.nesting.slabs_from_fields`); at
    ``refine > 1`` they do not and the slabs are **interpolated**
    (:func:`udprep.nesting.slabs_from_parent`), which is the only difference
    between V1 and V0 in this module.

    Keeping the two apart is what lets V0 point a child at data that did not
    come from the run it is compared against: the ``filtered`` arm drives the
    child from the fine reference's own dumps, box-filtered onto the coarse
    grid, while the ``coarse`` arm drives it from a genuinely coarse LES.  The
    child, the reference and every diagnostic are identical between them.
    """

    #: A :class:`caselib.FieldDump` or :class:`caselib.CoarsenedFieldDump`.
    dump: Any
    #: Experiment number of the *directory* the dumps were read from.
    source_expnr: str
    #: Spacing of the grid the data arrives on [m].
    dx: float
    #: ``dx / dx_child``.  1 reproduces V1 exactly.
    refine: int
    #: Factor the source directory's dumps are box-filtered by (1 unless the
    #: source is a finer run than the driving grid).
    coarsen: int
    #: Child window origin, in driving-grid columns.
    i0: int
    j0: int
    #: Driving grid extent, in its own cells.
    itot: int
    jtot: int
    ktot: int
    label: str

    # -- constructors ------------------------------------------------------- #

    @classmethod
    def matched(cls, parent_dir: Path, preset: Preset) -> "DrivingParent":
        """V1: parent and child on one grid, slabs cut rather than interpolated."""
        return cls(
            dump=FieldDump(parent_dir, preset.parent_expnr, preset.dx),
            source_expnr=preset.parent_expnr, dx=preset.dx, refine=1, coarsen=1,
            i0=preset.child_i0, j0=preset.child_j0,
            itot=preset.itot, jtot=preset.jtot, ktot=preset.ktot,
            label=f"{preset.parent_expnr} at {preset.dx:g} m (r = 1, slabs cut)",
        )

    @classmethod
    def refined(cls, parent_dir: Path, point: RefinedPoint) -> "DrivingParent":
        """V0: the driving grid is ``point.refine`` times coarser than the child's."""
        d, c = point.driver, point.child
        if point.coarsen > 1:
            dump: Any = CoarsenedFieldDump(
                FieldDump(parent_dir, point.reference_expnr, c.dx), point.coarsen)
            source = point.reference_expnr
            label = (f"{source} at {c.dx:g} m, box-filtered by {point.coarsen} "
                     f"onto the {d.dx:g} m grid (r = {point.refine}, slabs interpolated)")
        else:
            dump = FieldDump(parent_dir, d.parent_expnr, d.dx)
            source = d.parent_expnr
            label = (f"{source} at {d.dx:g} m "
                     f"(r = {point.refine}, slabs interpolated)")
        return cls(dump=dump, source_expnr=source, dx=d.dx, refine=point.refine,
                   coarsen=point.coarsen, i0=d.child_i0, j0=d.child_j0,
                   itot=d.itot, jtot=d.jtot, ktot=d.ktot, label=label)

    # -- derived ------------------------------------------------------------ #

    @property
    def interpolates(self) -> bool:
        return self.refine > 1

    def window_cells(self, preset: Preset) -> Tuple[int, int, int]:
        """The child window, in driving-grid cells."""
        return (int(round(preset.child_xlen / self.dx)),
                int(round(preset.child_ylen / self.dx)),
                int(round(preset.zsize / self.dx)))

    def grid(self, preset: Preset) -> NestGrid:
        """The driving grid over the child window, in the child's own coordinates.

        ``conservative_interpolate`` needs parent and child coordinates in one
        frame, and the child's frame has its origin at 0 -- so the parent is
        described here as the window only, not the whole domain.  Nothing is
        lost: the writer never interpolates outside the zone slabs and the
        optional initial-condition block, both of which are inside the window.
        """
        ni, nj, nk = self.window_cells(preset)
        return NestGrid.uniform(ni, nj, nk, preset.child_xlen, preset.child_ylen,
                                preset.zsize)

    def fluid_window(self, parent_dir: Path, preset: Preset) -> np.ndarray:
        """The driving parent's fluid mask over the window, on the reduced grid.

        Shape ``(ni - 1, nj - 1, nk - 1)`` to match :func:`caselib.cell_centred`.
        Read from the source directory at *its* resolution and block-ANDed down
        when the source is finer than the driving grid, so a coarse cell counts
        as fluid only if all of it is.
        """
        ni, nj, nk = self.window_cells(preset)
        c = self.coarsen
        fluid = load_solid_mask(parent_dir,
                                (self.itot * c, self.jtot * c, self.ktot * c))
        fluid = coarsen_fluid_mask(fluid, c)
        return fluid[self.i0:self.i0 + ni - 1,
                     self.j0:self.j0 + nj - 1, :nk - 1]

    def interior_columns(self, preset: Preset) -> Tuple[np.ndarray, np.ndarray]:
        """Reduced-array columns outside the guard + ramp, on the driving grid.

        The same rule ``analyse.interior_indices`` applies to the child, so the
        driving parent's own profile is taken over the region the child's
        statistics are taken over -- to within the coarse grid's ability to
        resolve its edges, which is why it is recomputed here rather than
        rescaled from the child's.
        """
        lz = preset.guardwidth + preset.zonewidth
        ni, nj, _ = self.window_cells(preset)
        i = np.arange(ni - 1)
        j = np.arange(nj - 1)
        return (np.where(((i + 0.5) * self.dx >= lz)
                         & ((ni - i - 0.5) * self.dx >= lz))[0],
                np.where(((j + 0.5) * self.dx >= lz)
                         & ((nj - j - 0.5) * self.dx >= lz))[0])


def build(parent_dir: Path, outdir: Path, preset: Preset,
          ibm_backend: str = "auto", margin_levels: int = 2,
          driving: Optional[DrivingParent] = None) -> Path:
    """Build the child case in ``outdir`` from the parent dumps in ``parent_dir``.

    ``driving`` says which grid the parent data arrives on.  ``None`` -- the V1
    and V2 case -- means the parent's own grid at ``preset.dx``, and the slabs
    are cut.  A :class:`DrivingParent` at ``refine > 1`` means the data arrives
    coarser and the slabs are interpolated through the production prolongation;
    ``parent_dir`` is then the directory that object was built against, which
    for V0's filtered arm is the *fine* reference run, not a coarse one.
    """
    nr = preset.child_expnr
    casedir = Path(outdir) / nr
    casedir.mkdir(parents=True, exist_ok=True)
    zf = (np.arange(preset.child_ktot) + 0.5) * preset.dz

    # ---- geometry and a placeholder profile, then preprocessing ---------- #
    # The child's own layout, which is the parent's restriction minus whatever
    # would have landed in the guard + ramp band (config.Preset.child_cube_centres,
    # design section 9.4).  For V1 that subtraction is empty and the child is an
    # exact sub-model of the parent; for the V2 size arm it is not, and the
    # difference is confined to the band -- Preset.validate refuses a preset
    # where a cleared cube would also reach the analysis interior.
    cube_geometry(preset, preset.child_origin[0], preset.child_origin[1],
                  preset.child_xlen, preset.child_ylen, casedir / f"geom.{nr}.stl",
                  centres=preset.child_cube_centres())
    write_prof(casedir / f"prof.inp.{nr}", zf, u=preset.u0, v=0.0, e12=preset.tke0,
               comment="placeholder; overwritten with the parent's own profile below")
    # pgx = 0 on purpose; the forcing lives in &PHYSICS dpdx.  See the
    # docstring of caselib.write_lscale before changing this.
    write_lscale(casedir / f"lscale.inp.{nr}", zf,
                 comment="V1 big-brother child: forcing is dpdx in &PHYSICS")

    if driving is None:
        driving = DrivingParent.matched(parent_dir, preset)
    dump = driving.dump
    all_times = np.asarray(dump.times, dtype=float)
    # -- the boundary cadence: which of the parent's levels the child gets -- #
    # Every ``stride``-th dumped level, chosen BEFORE anything is read: the
    # loop below reads levels by index, so the levels that are skipped are
    # never touched and the I/O of the slab cut shrinks with the cadence,
    # not just the array.  ``times``, ``n_use``, ``runtime``, ``t_offset``
    # and ``parent_dt`` are all taken from the subsampled axis.
    stride = preset.cadence_stride
    levels = np.arange(0, all_times.size, stride)
    times = all_times[levels]
    if times.size < 4:
        raise RuntimeError(
            f"the parent wrote {all_times.size} field dumps, {times.size} at a "
            f"{preset.cadence:g} s cadence (every {stride}); V1 needs a time series"
        )
    # Stop the child short of the last stored level so the target is always
    # interpolated, never held constant past the end of the record.
    n_use = times.size
    runtime = float(times[-1 - margin_levels] - times[0])
    parent_dt = float(np.median(np.diff(times)))
    print(f"[make_child_case] cadence {preset.cadence:g} s: every {stride} of "
          f"{all_times.size} parent levels -> {n_use} levels, dt_P = {parent_dt:.3f} s, "
          f"C_dump = {preset.c_dump_u0:.2f} at u0 = {preset.u0:g} m/s")

    write_namoptions(
        casedir / f"namoptions.{nr}",
        child_sections(preset, runtime),
        header=[
            f"V1 Big Brother child, preset '{preset.name}'",
            "generated by tests/validation/nesting/make_child_case.py; do not hand-edit",
            f"driven by {parent_dir}",
        ],
    )
    run_preprocessing(casedir, ibm_backend=ibm_backend)

    # ---- cut or interpolate the slabs, accumulating the profile on the way - #
    grid = child_grid(preset)
    pgrid = driving.grid(preset)
    pi0, pj0 = driving.i0, driving.j0
    pni, pnj, pnk = driving.window_cells(preset)
    nzone = preset.nzone
    # The profile that seeds prof.inp is accumulated on the grid the parent data
    # ARRIVES on, which is the child's own only at refinement ratio 1.  At r > 1
    # it is the coarse grid and the profile is interpolated onto the child's
    # levels at the end; interpolating every parent level onto the whole child
    # instead would cost about as much as the slab cut and buy nothing, since
    # prof.inp carries a horizontal mean.
    if driving.interpolates:
        fluid = driving.fluid_window(parent_dir, preset)
    else:
        # Fluid in the child AND in the parent.  The profile below is accumulated
        # from the *parent's* field, so a cell the child cleared out of its zone --
        # fluid in the child, solid in the parent -- would contribute the parent's
        # near-zero in-building velocity to it.  Same intersection, and same reason,
        # as analyse.run.  A no-op wherever the two geometries agree, i.e. always
        # unless clear_child_zone is set.
        shape = (preset.child_itot - 1, preset.child_jtot - 1, preset.child_ktot - 1)
        fluid = load_solid_mask(casedir, shape)
        if preset.clear_child_zone:
            pfluid = load_solid_mask(parent_dir, (preset.itot, preset.jtot, preset.ktot))
            fluid = fluid & pfluid[preset.child_i0:preset.child_i0 + shape[0],
                                   preset.child_j0:preset.child_j0 + shape[1], :shape[2]]
    nkp = fluid.shape[2]
    usum = np.zeros(nkp)
    vsum = np.zeros(nkp)
    ncell = fluid.sum(axis=(0, 1)).astype(float)
    ncell[ncell == 0] = np.nan
    # The driving parent's own interior statistics, on its own grid.  Free here
    # -- the loop already holds every level -- and the only way to tell a child
    # that failed to reproduce the truth from a child that faithfully reproduced
    # a parent which was itself wrong.  Reported by analyse_v0, never used to
    # drive anything.
    ii_p, jj_p = driving.interior_columns(preset)
    isel = fluid[np.ix_(ii_p, jj_p)]
    icell = isel.sum(axis=(0, 1)).astype(float)
    icell[icell == 0] = np.nan
    imean = {c: np.zeros(nkp) for c in "uvw"}
    imsq = {c: np.zeros(nkp) for c in "uvw"}

    # ---- the nesting file, through the production per-level writer ------- #
    # The temporal ratio parent_dt / dtmax -- the boundary cadence over the
    # child's CFL step -- exceeds the design's V5 bound of 30 for every
    # production preset.  That bound predates the cadence study (C0), whose
    # criterion is C_dump; the writer evaluates and logs it.  The violation
    # is allowed explicitly, with this reason, and the verdict is recorded in
    # the manifest below rather than silenced.
    refinement_reason = (
        "temporal ratio parent_dt/dtmax is the parent dump cadence over the child's "
        "CFL-limited step; the boundary cadence is bounded by C_dump instead"
    )
    # Each level is appended as soon as it is cut: the writer corrects its
    # divergence on arrival, stores the pre- and post-correction residuals, and
    # syncs and projects the initial condition against the corrected level 0.
    # Nothing but the current parent level is held, so the slab cut's memory
    # is set by the parent's level size, not by the record length -- the
    # production record (thousands of levels) does not fit any other way.
    # The correction is summed over all four lateral faces, as it was when
    # apply_divergence_correction ran here on the whole record; a preset whose
    # lateral faces cut buildings is where udprep.nesting.face_masks_from_ibm
    # would be passed as ``masks``, and where the file's fluid_lateral_area
    # would start to match the solver's.
    nestfile = casedir / f"nesting.inp.{nr}.nc"
    writer = NestingWriter(
        nestfile, grid, nzone,
        parent_model=f"udales:{driving.source_expnr}:{preset.name}",
        parent_dx=driving.dx,
        parent_dt=parent_dt,
        child_origin_x=preset.child_origin[0],
        child_origin_y=preset.child_origin[1],
        child_dt=preset.dtmax,
        allow_refinement_violation=True,
        refinement_reason=refinement_reason,
    )
    # Post-correction residual of every stored level, from the writer's own
    # recomputation of what it wrote -- the number the solver validates against.
    phi_after = np.empty(n_use, dtype=np.float64)
    has_initial = False
    div0 = None
    div_parent0 = None
    with writer:
        for n, lev in enumerate(levels):
            pu, pv, pw = dump.read_level(int(lev))
            cu, cv, cw = dump.child_block(pu, pv, pw, pi0, pj0, pni, pnj)
            initial_fields = None
            if n == 0 and preset.init_from_parent:
                # Schema 2's optional full-domain block: the child cold-starts from
                # the parent's own instantaneous field, so the interior turbulence
                # is the parent's from the first step instead of having to grow in
                # from the boundaries.  The writer syncs it to the corrected
                # boundary data of level 0 and projects it before storing it.
                if driving.interpolates:
                    initial_fields = initial_fields_from_parent(pgrid, cu, cv, cw, grid)
                    div0 = float(np.max(np.abs(discrete_divergence(
                        grid, initial_fields["u"], initial_fields["v"],
                        initial_fields["w"]))))
                    # Design section 1.3: the prolongation reproduces the parent's
                    # discrete divergence cell by cell, so a solenoidal parent gives
                    # a solenoidal child target.  Recording the parent's own divmax
                    # next to the child's turns that from an assertion in a docstring
                    # into a number in the manifest -- and it is the offline half of
                    # the end-to-end check the runtime `divmax` completes.
                    div_parent0 = float(np.max(np.abs(
                        discrete_divergence(pgrid, cu, cv, cw))))
                else:
                    # copies: the profile below still needs the parent's own field
                    initial_fields = {"u": cu.copy(), "v": cv.copy(), "w": cw.copy()}
                    div0 = float(np.max(np.abs(discrete_divergence(grid, cu, cv, cw))))
                has_initial = True
            if driving.interpolates:
                level = slabs_from_parent(pgrid, cu, cv, cw, child=grid, nzone=nzone)
            else:
                level = slabs_from_fields(grid, nzone, cu, cv, cw)
            phi_after[n] = writer.append_level(
                times[n] - times[0], level, initial_fields=initial_fields,
            )["flux_residual"]
            uc, vc, wc = caselib.cell_centred(cu[:-1], cv[:, :-1], cw[:, :, :-1])
            usum += np.where(fluid, uc, 0.0).sum(axis=(0, 1)) / ncell
            vsum += np.where(fluid, vc, 0.0).sum(axis=(0, 1)) / ncell
            for c, arr in zip("uvw", (uc, vc, wc)):
                blk = arr[np.ix_(ii_p, jj_p)]
                imean[c] += np.where(isel, blk, 0.0).sum(axis=(0, 1)) / icell
                imsq[c] += np.where(isel, blk * blk, 0.0).sum(axis=(0, 1)) / icell
    # cadence, correction and refinement, accumulated level by level in the
    # writer; the refinement verdict already carries "allowed" and the reason
    diagnostics = writer.diagnostics
    # Largest pre-correction |Phi| over the record, as the writer saw it arrive
    phi_before_max = float(diagnostics["correction"]["residual_max_abs"])
    phi_after_max = float(np.max(np.abs(phi_after)))
    # Total lateral boundary area -- the normalisation modnesting's
    # check_stored_flux uses (phi = sum(rho u_n dA) / area_bnd).
    area = 2.0 * (grid.xlen + grid.ylen) * grid.zsize
    # The stored initial condition is the synced and projected one; its
    # divergence is measured on what the solver will read, not on a copy.
    ic_after = _initial_condition_divmax(nestfile, grid) if has_initial else None

    pzf = (np.arange(nkp) + 0.5) * driving.dx
    if driving.interpolates:
        # The coarse profile carried onto the child's levels.  prof.inp only has
        # to start the child near equilibrium -- with nest_linitfromparent the
        # velocity field is overwritten by the interpolated parent block anyway
        # -- so linear interpolation, held constant outside the coarse range, is
        # ample and is not a claim about sub-parent-scale structure.
        uprof = np.interp(zf, pzf, usum / n_use)
        vprof = np.interp(zf, pzf, vsum / n_use)
        prof_comment = (f"driving parent ({driving.label}) time- and plane-mean "
                        f"profile, fluid cells only, interpolated from its "
                        f"{driving.dx:g} m levels")
    else:
        uprof = np.empty(preset.child_ktot)
        vprof = np.empty(preset.child_ktot)
        uprof[:-1] = usum / n_use
        vprof[:-1] = vsum / n_use
        uprof[-1] = uprof[-2]
        vprof[-1] = vprof[-2]
        prof_comment = ("parent sub-region time- and plane-mean profile "
                        "(fluid cells only)")
    write_prof(casedir / f"prof.inp.{nr}", zf, u=uprof, v=vprof, e12=preset.tke0,
               comment=prof_comment)
    driving_profile = {
        "grid": "driving parent, its own cell centres",
        "source": driving.label,
        "dx_m": driving.dx,
        "z": pzf.tolist(),
        "interior_columns": [int(ii_p.size), int(jj_p.size)],
        "u": (imean["u"] / n_use).tolist(),
        "v": (imean["v"] / n_use).tolist(),
        "w": (imean["w"] / n_use).tolist(),
        "tke": (0.5 * sum(imsq[c] / n_use - (imean[c] / n_use) ** 2
                          for c in "uvw")).tolist(),
        "note": ("interior-only, fluid-only, over the same guard + ramp exclusion "
                 "the child's statistics use, on the driving grid; this is what "
                 "the parent itself knew"),
    }

    # ---- the manifest ----------------------------------------------------- #
    manifest = {
        "preset": preset.name,
        "parent_dir": str(Path(parent_dir).resolve()),
        "refinement": {
            "spatial": driving.refine,
            "spatial_from_file": diagnostics["refinement"]["spatial"],
            "temporal_from_file": diagnostics["refinement"]["temporal"],
            "parent_dx_m": driving.dx,
            "child_dx_m": preset.dx,
            "parent_nyquist_wavelength_m": 2.0 * driving.dx,
            "source": driving.label,
            "source_expnr": driving.source_expnr,
            "coarsen_factor": driving.coarsen,
            "slabs": ("interpolated (slabs_from_parent)" if driving.interpolates
                      else "cut (slabs_from_fields)"),
            "parent_window_cells": [pni, pnj, pnk],
            "check": diagnostics["refinement"],
        },
        # NestingWriter.diagnostics as it is: ntime, cadence, correction and
        # the refinement verdict (the same object as refinement.check above)
        "writer_diagnostics": diagnostics,
        "driving_parent_profile": driving_profile,
        "child_expnr": nr,
        "parent_expnr": preset.parent_expnr,
        "t_offset": float(times[0]),
        "runtime": runtime,
        "n_parent_levels": int(n_use),
        "parent_dt_median": parent_dt,
        "cadence": {
            "seconds": float(preset.cadence),
            "stride": int(stride),
            "parent_dt": parent_dt,
            "dump_dt": float(preset.dtdump),
            "n_levels_dumped": int(all_times.size),
            "n_levels_used": int(n_use),
            "child_dtdump": float(preset.child_dtdump),
            "C_dump_at_u0": float(preset.c_dump_u0),
            "u0": float(preset.u0),
            "note": ("every 'stride'-th parent dump level is read and stored; the "
                     "others are never opened.  C_dump = u0 * cadence / dx is a "
                     "label at the initial bulk wind, not the criterion, which is "
                     "evaluated at the largest wind in the zone"),
        },
        "stats_start": float(preset.child_spinup),
        "child_i0": preset.child_i0,
        "child_j0": preset.child_j0,
        "ustar": preset.ustar,
        "dpdx": preset.dpdx,
        "flux_residual_before_correction": {
            "max_abs": phi_before_max,
            "max_abs_normalised": phi_before_max / area,
        },
        "flux_residual_after_correction": {
            "max_abs": phi_after_max,
            "max_abs_normalised": phi_after_max / area,
        },
        "nest_timeinterp": preset.timeinterp,
        "init_from_parent": bool(preset.init_from_parent),
        "geometry": preset.geometry,
        "building_free_zone": bool(preset.building_free_zone),
        "n_cubes_parent": int(len(preset.cube_centres())),
        "n_cubes_child": int(len(preset.child_cube_centres())),
        "n_cubes_child_in_parent_window": int(len(preset.cube_centres_in(
            preset.child_origin[0], preset.child_origin[1],
            preset.child_xlen, preset.child_ylen))),
        "clear_child_zone": bool(preset.clear_child_zone),
        "n_cubes_cleared_from_child_zone": int(preset.n_child_cubes_removed),
        "initial_condition_divmax": {
            "parent_before_prolongation": div_parent0,
            "before_projection": div0,
            "after_projection": ic_after,
        },
    }
    (casedir / "manifest.json").write_text(json.dumps(manifest, indent=2) + "\n",
                                           encoding="ascii")
    return casedir


def _initial_condition_divmax(nestfile: Path, grid: NestGrid) -> float:
    """Peak discrete divergence of the ``u_init``/``v_init``/``w_init`` block stored in ``nestfile``.

    Read back directly rather than through ``read_nesting_file``, which would
    load every slab level -- the record the streaming cut just avoided holding.
    """
    from netCDF4 import Dataset

    with Dataset(nestfile, "r") as ds:
        fields = [np.asarray(ds.variables[f"{c}_init"][:], dtype=np.float64)
                  for c in COMPONENTS]
    return float(np.max(np.abs(discrete_divergence(grid, *fields))))


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("parent_dir", type=Path)
    parser.add_argument("outdir", type=Path)
    parser.add_argument("--preset", default="production")
    parser.add_argument("--ibm-backend", default="auto")
    args = parser.parse_args()

    preset = get_preset(args.preset)
    casedir = build(args.parent_dir, args.outdir, preset, ibm_backend=args.ibm_backend)
    manifest = json.loads((casedir / "manifest.json").read_text())
    print(f"child case written to {casedir}")
    cad = manifest["cadence"]
    print(f"  {manifest['n_parent_levels']} parent levels (every {cad['stride']} of "
          f"{cad['n_levels_dumped']} dumped; cadence {cad['seconds']:g} s), dt_P = "
          f"{manifest['parent_dt_median']:.3f} s, child runtime {manifest['runtime']:.1f} s")
    print(f"  Phi before correction  max |Phi|/A = "
          f"{manifest['flux_residual_before_correction']['max_abs_normalised']:.3e} m/s")
    print(f"  Phi after correction   max |Phi|/A = "
          f"{manifest['flux_residual_after_correction']['max_abs_normalised']:.3e} m/s")
    ic = manifest["initial_condition_divmax"]
    if ic["before_projection"] is not None:
        print(f"  initial condition divmax {ic['before_projection']:.3e} -> "
              f"{ic['after_projection']:.3e} after projection")


if __name__ == "__main__":
    main()
