#!/usr/bin/env python3
"""Cut the nested child case out of the parent's output.

Given a parent case directory that has finished its production phase, this
builds a complete, runnable child case:

* the same aligned cube array on the child's sub-domain -- generated by the
  same ``udgeom.create_cubes`` call, which reproduces the parent's array exactly
  because the child's origin is a whole number of cube periods;
* ``prof.inp`` seeded with the parent sub-region's own time- and
  plane-averaged ``<u>(z)``, ``<v>(z)`` so the child starts near equilibrium;
* ``namoptions.<nr>`` with ``lnesting = .true.`` and the zone geometry of the
  preset;
* ``nesting.inp.<nr>.nc``, written through the **production** writer
  ``tools/python/udprep/nesting.py`` (``slabs_from_fields`` +
  ``apply_divergence_correction`` + ``write_nesting_file``), so the writer and
  the Fortran reader cannot drift apart.

Because the refinement ratio is exactly 1 the slabs are *cut*, not interpolated
(``slabs_from_fields``): V1 is meant to isolate the nesting scheme from the
interpolation, which P1-P11 cover separately.

The child's clock starts at 0, so the parent dump times are shifted by
``t_offset = times[0]``.  ``manifest.json`` records the mapping.

Usage
-----
    python make_child_case.py <parent_case_dir> <outdir> [--preset ...]
"""

from __future__ import annotations

import argparse
import json
from collections import OrderedDict
from pathlib import Path
from typing import Dict, Tuple

import numpy as np

import caselib
from caselib import (
    FieldDump,
    cube_geometry,
    load_solid_mask,
    run_preprocessing,
    write_lscale,
    write_namoptions,
    write_prof,
)
from config import Preset, get_preset

from udprep.nesting import (
    NestGrid,
    NestingData,
    SLAB_VARIABLES,
    apply_divergence_correction,
    discrete_divergence,
    net_volume_flux,
    slab_shape,
    slabs_from_fields,
    write_nesting_file,
)


def child_sections(preset: Preset, runtime: float) -> "OrderedDict":
    nr = preset.child_expnr
    return OrderedDict([
        ("RUN", OrderedDict([
            ("iexpnr", int(nr)),
            ("runmode", 1),
            ("runtime", runtime),
            ("dtmax", preset.dtmax),
            ("ladaptive", True),
            ("trestart", 1.0e9),
            ("lwarmstart", False),
            ("startfile", f"initd00000000_000_000.{nr}"),
            ("irandom", 43),
            ("randu", 0.1 * preset.u0),
            ("krand", preset.child_ktot),
            ("lrandomize", True),
            ("libm", True),
            ("lles", True),
            ("nprocx", preset.child_nprocx),
            ("nprocy", preset.child_nprocy),
        ])),
        ("DOMAIN", OrderedDict([
            ("itot", preset.child_itot),
            ("jtot", preset.child_jtot),
            ("ktot", preset.child_ktot),
            ("xlen", preset.child_xlen),
            ("ylen", preset.child_ylen),
        ])),
        ("PHYSICS", OrderedDict([
            ("ltempeq", False),
            ("lmoist", False),
            ("lbuoyancy", False),
            ("lcoriol", False),
            ("lprofforc", False),
            ("luvolflowr", False),
            ("lvvolflowr", False),
            ("igrw_damp", 0),
            # Identical to the parent's: the two runs must share the momentum
            # source exactly, or the comparison measures the forcing difference.
            ("dpdx", preset.dpdx),
        ])),
        ("DYNAMICS", OrderedDict([
            ("ipoiss", 0),  # POISS_FFT2D; lnesting requires it
        ])),
        ("BC", OrderedDict([
            ("BCxm", 4),   # BCxm_nesting
            ("BCym", 3),   # BCym_nesting
            ("BCbotm", 3),
            ("BCtopm", 1),
        ])),
        ("NAMSUBGRID", OrderedDict([
            ("lvreman", True),
        ])),
        ("WALLS", OrderedDict([
            ("iwallmom", 2),
            ("iwalltemp", 1),
            ("lwritefac", False),
        ])),
        ("NESTING", OrderedDict([
            ("lnesting", True),
            ("nestfile", f"nesting.inp.{nr}.nc"),
            ("nest_guardwidth", preset.guardwidth),
            ("nest_zonewidth", preset.zonewidth),
            ("nest_tau", preset.tau),
            ("nest_shape", 1),        # raised cosine
            # 1 = linear.  Mode 2 (monotone Hermite) is NOT flux safe -- its
            # Fritsch-Carlson slope limiter is nonlinear in the buffered levels,
            # so Phi = 0 is not preserved between parent levels.  See config.py
            # and README.md, "Finding N1".
            ("nest_timeinterp", preset.timeinterp),
            ("nest_nwall", preset.nwall),
            # .false. asserts the design section 5 rule -- no solid points
            # anywhere W > 0 -- instead of merely warning about it.  The 'plaza'
            # geometry earns that by removing, from the *parent*, the cubes whose
            # footprint would fall in the child's guard + ramp band, so the zone
            # sits over open ground.  The 'uniform' geometry keeps the unbroken
            # array and needs .true.: legal only because the parent resolves the
            # same buildings (self-nesting), and the harder case.
            ("nest_lparentgeom", not preset.building_free_zone),
            ("nest_fluxtol", 1.0e-10),
            ("nest_lfluxassert", True),
            ("nest_linitfromparent", preset.init_from_parent),
        ])),
        ("NAMCHECKSIM", OrderedDict([
            ("tcheck", max(1.0, runtime / 20.0)),
        ])),
        ("OUTPUT", OrderedDict([
            ("lfielddump", True),
            ("tfielddump", preset.dtdump),
            ("fieldvars", "u0,v0,w0"),
        ])),
        ("INP", OrderedDict([
            ("zsize", preset.zsize),
            ("stl_file", f"geom.{nr}.stl"),
            ("u0", preset.u0),
            ("v0", 0.0),
            ("thl0", 288.0),
        ])),
    ])


def child_grid(preset: Preset) -> NestGrid:
    """The child's own grid, origin at 0 -- what ``nestio_validate`` compares."""
    return NestGrid.uniform(
        preset.child_itot, preset.child_jtot, preset.child_ktot,
        preset.child_xlen, preset.child_ylen, preset.zsize,
    )


def build(parent_dir: Path, outdir: Path, preset: Preset,
          ibm_backend: str = "auto", margin_levels: int = 2) -> Path:
    nr = preset.child_expnr
    casedir = Path(outdir) / nr
    casedir.mkdir(parents=True, exist_ok=True)
    zf = (np.arange(preset.child_ktot) + 0.5) * preset.dz

    # ---- geometry and a placeholder profile, then preprocessing ---------- #
    cube_geometry(preset, preset.child_origin[0], preset.child_origin[1],
                  preset.child_xlen, preset.child_ylen, casedir / f"geom.{nr}.stl")
    write_prof(casedir / f"prof.inp.{nr}", zf, u=preset.u0, v=0.0, e12=preset.tke0,
               comment="placeholder; overwritten with the parent's own profile below")
    # pgx = 0 on purpose; the forcing lives in &PHYSICS dpdx.  See the
    # docstring of caselib.write_lscale before changing this.
    write_lscale(casedir / f"lscale.inp.{nr}", zf,
                 comment="V1 big-brother child: forcing is dpdx in &PHYSICS")

    dump = FieldDump(parent_dir, preset.parent_expnr, preset.dx)
    times = np.asarray(dump.times, dtype=float)
    if times.size < 4:
        raise RuntimeError(
            f"the parent wrote only {times.size} field dumps; V1 needs a time series"
        )
    # Stop the child short of the last stored level so the target is always
    # interpolated, never held constant past the end of the record.
    n_use = times.size
    runtime = float(times[-1 - margin_levels] - times[0])

    write_namoptions(
        casedir / f"namoptions.{nr}",
        child_sections(preset, runtime),
        header=[
            f"V1 Big Brother child, preset '{preset.name}'",
            "generated by tests/validation/nesting/make_child_case.py; do not hand-edit",
            f"driven by {parent_dir}",
        ],
    )
    run_preprocessing(casedir, ibm_backend=ibm_backend)

    # ---- cut the slabs, accumulating the mean profile on the way --------- #
    grid = child_grid(preset)
    nzone = preset.nzone
    slabs: Dict[str, np.ndarray] = {
        name: np.empty((n_use,) + slab_shape(grid, nzone, *_split(name)),
                       dtype=np.float64)
        for name in SLAB_VARIABLES
    }
    fluid = load_solid_mask(casedir,
                            (preset.child_itot - 1, preset.child_jtot - 1,
                             preset.child_ktot - 1))
    usum = np.zeros(preset.child_ktot - 1)
    vsum = np.zeros(preset.child_ktot - 1)
    ncell = fluid.sum(axis=(0, 1)).astype(float)
    ncell[ncell == 0] = np.nan

    initial_fields = None
    div0 = None
    for n in range(n_use):
        pu, pv, pw = dump.read_level(n)
        cu, cv, cw = dump.child_block(pu, pv, pw, preset.child_i0, preset.child_j0,
                                      preset.child_itot, preset.child_jtot)
        if n == 0 and preset.init_from_parent:
            # Schema 2's optional full-domain block: the child cold-starts from
            # the parent's own instantaneous field, so the interior turbulence
            # is the parent's from the first step instead of having to grow in
            # from the boundaries.  apply_divergence_correction() below syncs it
            # to the corrected boundary data and projects it.
            initial_fields = {"u": cu.copy(), "v": cv.copy(), "w": cw.copy()}
            div0 = float(np.max(np.abs(discrete_divergence(grid, cu, cv, cw))))
        level = slabs_from_fields(grid, nzone, cu, cv, cw)
        for name, arr in level.items():
            slabs[name][n] = arr
        uc, vc, _ = caselib.cell_centred(cu[:-1], cv[:, :-1], cw[:, :, :-1])
        usum += np.where(fluid, uc, 0.0).sum(axis=(0, 1)) / ncell
        vsum += np.where(fluid, vc, 0.0).sum(axis=(0, 1)) / ncell

    uprof = np.empty(preset.child_ktot)
    vprof = np.empty(preset.child_ktot)
    uprof[:-1] = usum / n_use
    vprof[:-1] = vsum / n_use
    uprof[-1] = uprof[-2]
    vprof[-1] = vprof[-2]
    write_prof(casedir / f"prof.inp.{nr}", zf, u=uprof, v=vprof, e12=preset.tke0,
               comment="parent sub-region time- and plane-mean profile "
                       "(fluid cells only)")

    # ---- write the nesting file through the production writer ------------ #
    data = NestingData(
        grid=grid,
        nzone=nzone,
        times=times[:n_use] - times[0],
        slabs=slabs,
        parent_model=f"udales:{preset.parent_expnr}:{preset.name}",
        parent_dx=preset.dx,
        parent_dt=float(np.median(np.diff(times[:n_use]))),
        child_origin_x=preset.child_origin[0],
        child_origin_y=preset.child_origin[1],
        child_dt=preset.dtmax,
        initial_fields=initial_fields,
    )
    phi_before = net_volume_flux(data)
    apply_divergence_correction(data)
    phi_after = net_volume_flux(data)
    # Total lateral boundary area -- the normalisation modnesting's
    # check_stored_flux uses (phi = sum(rho u_n dA) / area_bnd).
    area = 2.0 * (grid.xlen + grid.ylen) * grid.zsize
    write_nesting_file(casedir / f"nesting.inp.{nr}.nc", data, override=True)

    manifest = {
        "preset": preset.name,
        "parent_dir": str(Path(parent_dir).resolve()),
        "child_expnr": nr,
        "parent_expnr": preset.parent_expnr,
        "t_offset": float(times[0]),
        "runtime": runtime,
        "n_parent_levels": int(n_use),
        "parent_dt_median": float(np.median(np.diff(times[:n_use]))),
        "stats_start": float(preset.child_spinup),
        "child_i0": preset.child_i0,
        "child_j0": preset.child_j0,
        "ustar": preset.ustar,
        "dpdx": preset.dpdx,
        "flux_residual_before_correction": {
            "max_abs": float(np.max(np.abs(phi_before))),
            "max_abs_normalised": float(np.max(np.abs(phi_before)) / area),
        },
        "flux_residual_after_correction": {
            "max_abs": float(np.max(np.abs(phi_after))),
            "max_abs_normalised": float(np.max(np.abs(phi_after)) / area),
        },
        "nest_timeinterp": preset.timeinterp,
        "init_from_parent": bool(preset.init_from_parent),
        "geometry": preset.geometry,
        "building_free_zone": bool(preset.building_free_zone),
        "n_cubes_parent": int(len(preset.cube_centres())),
        "n_cubes_child": int(len(preset.cube_centres_in(
            preset.child_origin[0], preset.child_origin[1],
            preset.child_xlen, preset.child_ylen))),
        "initial_condition_divmax": {
            "before_projection": div0,
            "after_projection": (
                None if initial_fields is None else float(np.max(np.abs(
                    discrete_divergence(grid, data.initial_fields["u"],
                                        data.initial_fields["v"],
                                        data.initial_fields["w"]))))
            ),
        },
    }
    (casedir / "manifest.json").write_text(json.dumps(manifest, indent=2) + "\n",
                                           encoding="ascii")
    return casedir


def _split(name: str) -> Tuple[str, str]:
    component, face = name.split("_", 1)
    return face, component


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("parent_dir", type=Path)
    parser.add_argument("outdir", type=Path)
    parser.add_argument("--preset", default="production")
    parser.add_argument("--ibm-backend", default="auto")
    args = parser.parse_args()

    preset = get_preset(args.preset)
    casedir = build(args.parent_dir, args.outdir, preset, ibm_backend=args.ibm_backend)
    manifest = json.loads((casedir / "manifest.json").read_text())
    print(f"child case written to {casedir}")
    print(f"  {manifest['n_parent_levels']} parent levels, dt_P = "
          f"{manifest['parent_dt_median']:.3f} s, child runtime {manifest['runtime']:.1f} s")
    print(f"  Phi before correction  max |Phi|/A = "
          f"{manifest['flux_residual_before_correction']['max_abs_normalised']:.3e} m/s")
    print(f"  Phi after correction   max |Phi|/A = "
          f"{manifest['flux_residual_after_correction']['max_abs_normalised']:.3e} m/s")
    ic = manifest["initial_condition_divmax"]
    if ic["before_projection"] is not None:
        print(f"  initial condition divmax {ic['before_projection']:.3e} -> "
              f"{ic['after_projection']:.3e} after projection")


if __name__ == "__main__":
    main()
